# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                        QgsProcessingParameterFeatureSink,
                        QgsProcessingParameterNumber,
                        QgsFields,
                        QgsField,
                        QgsProcessingParameterBoolean,
                        QgsWkbTypes,
                        QgsProcessingParameterRasterLayer
                        )
from .algorithms.auxiliarys.SLindex import calculateSLindexGeometry,verifyLibs

class slIndexCalc(QgsProcessingAlgorithm):
    '''
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    '''

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    DRAINAGE_BASINS = 'DRAINAGE_BASINS'
    CHANNEL_NETWORK = 'CHANNEL_NETWORK'
    CHANNEL_COORDINATE_PRECISION = 'CHANNEL_COORDINATE_PRECISION'
    MINIMUM_CHANNEL_LENGTH = 'MINIMUM_CHANNEL_LENGTH'
    SL_INDEX_POINTS = 'SL_INDEX_POINTS'
    SL_INDEX_STEPS = 'SL_INDEX_STEPS'
    SL_INDEX_DISTANCES = 'SL_INDEX_DISTANCES'
    USE_LONGEST_DRAINAGE = 'USE_LONGEST_DRAINAGE'
    DEM = 'DEM'
    N_SECTIONS_SL = 'N_SECTIONS_SL'

    def initAlgorithm(self, config):
        '''
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        '''

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.DRAINAGE_BASINS,
                self.tr('Drainage basins'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.CHANNEL_NETWORK,
                self.tr('Channel network'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DEM,
                self.tr('DEM'),
                [QgsProcessing.TypeRaster]
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.N_SECTIONS_SL,
                self.tr('Number of sections for SL index'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=1,
                defaultValue=10
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.USE_LONGEST_DRAINAGE,
                self.tr('Use lch as longest drainage and not the main channel'),
                defaultValue=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.CHANNEL_COORDINATE_PRECISION,
                self.tr('Channel coordinate precision'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0,
                defaultValue=0.000001,
                optional=True
            )
        )

        # We add the minimum channel length input.
        self.addParameter(
            QgsProcessingParameterNumber(
                self.MINIMUM_CHANNEL_LENGTH,
                self.tr('Minimum channel length'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0,
                defaultValue=0.000001,
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.SL_INDEX_POINTS,
                self.tr('SL index center points'))
            )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.SL_INDEX_DISTANCES,
                self.tr('SL index distances'))
            )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.SL_INDEX_STEPS,
                self.tr('SL index steps'))
            )

    def processAlgorithm(self, parameters, context, feedback):
        '''
        Here is where the processing itself takes place.
        '''

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        basinSource = self.parameterAsSource(parameters, self.DRAINAGE_BASINS, context)

        channelNetworkSource = self.parameterAsSource(parameters, self.CHANNEL_NETWORK, context)

        demLayer = self.parameterAsRasterLayer(parameters, self.DEM, context)

        precisionSnapCoordinates = self.parameterAsDouble(parameters, self.CHANNEL_COORDINATE_PRECISION, context)

        minimumChannelLength = self.parameterAsDouble(parameters, self.MINIMUM_CHANNEL_LENGTH, context)

        useLongestDrainage = self.parameterAsBool(parameters, self.USE_LONGEST_DRAINAGE, context)

        nSectionsSL = self.parameterAsInt(parameters, self.N_SECTIONS_SL, context)

        slIndexPointsFields = QgsFields()

        slIndexPointsFields.append(
            QgsField(
                "basin_id",
                QVariant.Int
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "section",
                QVariant.Int
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "delta_L",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "dist_L",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "up_elev",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "down_elev",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "diff_elev",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "SL",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "SLm",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "SLt",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "SLtm",
                QVariant.Double
            )
        )

        slIndexPointsFields.append(
            QgsField(
                "SLm/SLtm",
                QVariant.Double
            )
        )

        slIndexStepsFields = QgsFields()

        slIndexStepsFields.append(
            QgsField(
                "basin_id",
                QVariant.Int
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "section",
                QVariant.Int
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "delta_L",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "dist_L",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "up_elev",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "down_elev",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "diff_elev",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "SL",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "SLm",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "SLt",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "SLtm",
                QVariant.Double
            )
        )

        slIndexStepsFields.append(
            QgsField(
                "SLm/SLtm",
                QVariant.Double
            )
        )

        slIndexDistancesFields = QgsFields()

        slIndexDistancesFields.append(
            QgsField(
                "basin_id",
                QVariant.Int
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "section",
                QVariant.Int
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "delta_L",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "dist_L",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "up_elev",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "down_elev",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "diff_elev",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "SL",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "SLm",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "SLt",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "SLtm",
                QVariant.Double
            )
        )

        slIndexDistancesFields.append(
            QgsField(
                "SLm/SLtm",
                QVariant.Double
            )
        )

        slIndexSteps, pathSteps = self.parameterAsSink(
            parameters,
            self.SL_INDEX_STEPS,
            context,
            slIndexStepsFields,
            QgsWkbTypes.LineString,
            basinSource.sourceCrs()
        )

        slIndexPoints, pathPoints = self.parameterAsSink(
            parameters,
            self.SL_INDEX_POINTS,
            context,
            slIndexPointsFields,
            QgsWkbTypes.Point,
            basinSource.sourceCrs()
        )

        slIndexDistances, pathDistances = self.parameterAsSink(
            parameters,
            self.SL_INDEX_DISTANCES,
            context,
            slIndexDistancesFields,
            QgsWkbTypes.LineString,
            basinSource.sourceCrs()
        )

        verifyLibs()
        calculateSLindexGeometry(basinSource, channelNetworkSource, demLayer, feedback, precisionSnapCoordinates, minimumChannelLength, useLongestDrainage, slIndexSteps, slIndexPoints, slIndexDistances, nSectionsSL)

        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.SL_INDEX_STEPS: pathSteps, 
                self.SL_INDEX_POINTS: pathPoints,
                self.SL_INDEX_DISTANCES: pathDistances}

    def name(self):
        '''
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        '''
        return 'Calculate SL index'

    def displayName(self):
        '''
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        '''
        return self.tr(self.name())

    def groupId(self):
        return "basin_auxiliary"

    def group(self):
        '''
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        '''
        return self.tr("Auxiliary")

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QIcon(os.path.join(os.path.dirname(__file__), "icon.png"))

    def shortHelpString(self):
        """
        Returns a localised short help string for the algorithm.
        """
        return self.tr("""
        <html>
            <body>
                <p>       
        This tool calculates straight lines starting from the main channel or the longest channel.              
                </p>
        It is related to the calculation of the sinuosity index, fitness ratio, wandering ratio, gradient ratio, valley floor-to-valley height ratio, transverse topographic symmetry factor, and asymmetry factor.
                <p>
        <strong>Drainage basins: </strong>Layer containing drainage basins as features.
        <strong>Channel network: </strong>Layer containing the drainage network of the drainage basins.
        <strong>DEM: </strong>Raster containing the band with the altimetry of the drainage basins.
        <strong>Number of sections for SL index: </strong>It is the number of sections used to calculate the SL index.
        <strong>Use lch as longest drainage and not the main channel: </strong>The plugin default is to use the lch as main channel (hightest strahler order) but in some cases lch as longest drainage can be more useful. If this box is checked, the largest channel will be used as LCH in the calculations (see README).
        <strong>Channel coordinate precision: </strong>It is the precision of the channel coordinates, for example: for a precision of 0.000001 the coordinate xxxxxx.xxxxxxxxxxxx becomes xxxxxx.xxxxxx. It is recommended to use 0.000001 to correct possible geometry errors when selecting channels that intersect the basin. If it is 0, there will be no rounding.
        <strong>Minimum channel length: </strong>It is used to correct intersection errors, as well as channel network precision.
        <strong>SL index center points: </strong>The center point of each SL step.
        <strong>SL index distances: </strong>The distance from the central point to the point furthest upstream in the channel.
        <strong>SL index steps: </strong>The SL step equally spaced.

        The use of a projected CRS is recommended (the plugin calculation assumes that all input layers are in projected coordinate reference systems).
                       
        If you need more information about how the plugin works, such as the calculations it performs, among other things, access: https://github.com/JoaoVitorPimenta/qgis-plugin-Drainage-Basin-Geomorphology
        If you have found any bugs, errors or have any requests to make, among other things, please acess: https://github.com/JoaoVitorPimenta/qgis-plugin-Drainage-Basin-Geomorphology/issues
        If you need training for the plugin, or want to contact the plugin author for any reason, send an email to: jvpjoaopimentadev@gmail.com
                </p>
            </body>
        </html>
                    """)

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return slIndexCalc()
