# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterRasterLayer)
from .algorithms.parametersProcessing import calculateTectonicParameters,verifyLibs

class tectonicParametersCalc(QgsProcessingAlgorithm):
    '''
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    '''

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    TECTONIC_PARAMETERS = 'TECTONIC_PARAMETERS'
    DRAINAGE_BASINS = 'DRAINAGE_BASINS'
    DEM = 'DEM'
    LIMIT_FOR_VALLEY_FLOOR = 'LIMIT_FOR_VALLEY_FLOOR'
    MIN_FOR_VALLEY_HEIGHT = 'MIN_FOR_VALLEY_HEIGHT'
    USE_LONGEST_DRAINAGE = 'USE_LONGEST_DRAINAGE'
    CHANNEL_COORDINATE_PRECISION = 'CHANNEL_COORDINATE_PRECISION'
    CHANNEL_NETWORK = 'CHANNEL_NETWORK'
    DECIMAL_PLACES = 'DECIMAL_PLACES'
    MINIMUM_CHANNEL_LENGTH = 'MINIMUM_CHANNEL_LENGTH'
    POINTS_TTSF = 'POINTS_TTSF'
    POINTS_MIDLINE = 'POINTS_MIDLINE'
    N_SECTIONS_SL = 'N_SECTIONS_SL'

    def initAlgorithm(self, config):
        '''
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        '''

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.DRAINAGE_BASINS,
                self.tr('Drainage basins'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.CHANNEL_NETWORK,
                self.tr('Channel network'),
                [QgsProcessing.TypeVectorLine]
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DEM,
                self.tr('DEM'),
                [QgsProcessing.TypeRaster]
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.N_SECTIONS_SL,
                self.tr('Number of sections for SL index'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=1,
                defaultValue=10
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.LIMIT_FOR_VALLEY_FLOOR,
                self.tr('Limit for valley floor'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0,
                defaultValue=0.1,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.MIN_FOR_VALLEY_HEIGHT,
                self.tr('Minimum height for valley peak'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0,
                defaultValue=1.0,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.POINTS_MIDLINE,
                self.tr('Number of points to create midline'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=2,
                defaultValue=50,
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.POINTS_TTSF,
                self.tr('Number of points to calculate TTSF'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=0,
                defaultValue=50,
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.USE_LONGEST_DRAINAGE,
                self.tr('Use lch as longest drainage and not the main channel'),
                defaultValue=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.CHANNEL_COORDINATE_PRECISION,
                self.tr('Channel coordinate precision'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0,
                defaultValue=0.000001,
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.MINIMUM_CHANNEL_LENGTH,
                self.tr('Minimum channel length'),
                type=QgsProcessingParameterNumber.Double,
                minValue=0,
                defaultValue=0.000001,
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.DECIMAL_PLACES,
                self.tr('Decimal places of the result'),
                type=QgsProcessingParameterNumber.Integer,
                minValue=0,
                defaultValue=2,
                optional=False
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.TECTONIC_PARAMETERS,
                self.tr('Tectonic parameters'),
                fileFilter=('CSV files (*.csv)')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        '''
        Here is where the processing itself takes place.
        '''

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        basinSource = self.parameterAsSource(parameters, self.DRAINAGE_BASINS, context)

        channelNetwork = self.parameterAsSource(parameters, self.CHANNEL_NETWORK, context)

        demLayer = self.parameterAsRasterLayer(parameters, self.DEM, context)

        precisionSnapCoordinates = self.parameterAsDouble(parameters, self.CHANNEL_COORDINATE_PRECISION, context)

        minimumChannelLength = self.parameterAsDouble(parameters, self.MINIMUM_CHANNEL_LENGTH, context)

        decimalPlaces = self.parameterAsInt(parameters, self.DECIMAL_PLACES, context)

        path = self.parameterAsFileOutput(parameters, self.TECTONIC_PARAMETERS, context)

        pointsTTSF = self.parameterAsInt(parameters, self.POINTS_TTSF, context)

        pointsMidline = self.parameterAsInt(parameters, self.POINTS_MIDLINE, context)

        limitForValleyFloor = self.parameterAsDouble(parameters, self.LIMIT_FOR_VALLEY_FLOOR, context)

        minForValleyHeight = self.parameterAsDouble(parameters, self.MIN_FOR_VALLEY_HEIGHT, context)

        useLongestDrainage = self.parameterAsBoolean(parameters, self.USE_LONGEST_DRAINAGE, context)

        nSectionsSL = self.parameterAsInt(parameters, self.N_SECTIONS_SL, context)

        verifyLibs()
        calculateTectonicParameters(basinSource,channelNetwork,demLayer,path,feedback,precisionSnapCoordinates,decimalPlaces,minimumChannelLength,pointsTTSF,limitForValleyFloor,minForValleyHeight,useLongestDrainage,pointsMidline,nSectionsSL)

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.TECTONIC_PARAMETERS: path}

    def name(self):
        '''
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        '''
        return 'Calculate tectonic parameters'

    def displayName(self):
        '''
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        '''
        return self.tr(self.name())

    def groupId(self):
        return "basin_morph_params"

    def group(self):
        '''
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        '''
        return self.tr("Basin morphometric parameters")

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        return QIcon(os.path.join(os.path.dirname(__file__), "icon.png"))

    def shortHelpString(self):
        """
        Returns a localised short help string for the algorithm.
        """
        return self.tr("""
        <html>
            <body>
                <p>       
        This tool calculates all tectonic parameters of each basin feature individually.               
                </p>
                <p>
        <strong>Drainage basins: </strong>Layer containing drainage basins as features.
        <strong>Channel network: </strong>Layer containing the drainage network of the drainage basins.
        <strong>DEM: </strong>Raster containing the band with the altimetry of the drainage basins. 
        <strong>Limit for valley floor: </strong>Its the height limit to calculate the valley floor.
        <strong>Minimum height for valley: </strong>Its the minimum height difference between one point and and next point to consider a valley peak. A valley peak is defined as the first point preceding a downward slope. A minimum threshold is applied to prevent minor dips which could result from inaccuracies from being counted.
        <strong>Number of points for midline: </strong>Its the number of points to create the midline of the basin.
        <strong>Number of points for TTSF: </strong>Its the number of points in the midline to calculate the TTSF.
        <strong>Use lch as longest drainage and not the main channel: </strong>The plugin default is to use the lch as main channel (hightest strahler order) but in some cases lch as longest drainage can be more useful. If this box is checked, the largest channel will be used as LCH in the calculations (see README).
        <strong>Channel coordinate precision: </strong>It is the precision of the channel coordinates, for example: for a precision of 0.000001 the coordinate xxxxxx.xxxxxxxxxxxx becomes xxxxxx.xxxxxx. It is recommended to use 0.000001 to correct possible geometry errors when selecting channels that intersect the basin. If it is 0, there will be no rounding.
        <strong>Minimum channel length: </strong>It is used to correct intersection errors, as well as channel network precision.
        <strong>Tectonic parameters: </strong>File with all tectonic parameters calculated individually for each basin.
        
        The use of a projected CRS is recommended (the plugin calculation assumes that all input layers are in projected coordinate reference systems).
                       
        If you need more information about how the plugin works, such as the calculations it performs, among other things, access: https://github.com/JoaoVitorPimenta/qgis-plugin-Drainage-Basin-Geomorphology
        If you have found any bugs, errors or have any requests to make, among other things, please acess: https://github.com/JoaoVitorPimenta/qgis-plugin-Drainage-Basin-Geomorphology/issues
        If you need training for the plugin, or want to contact the plugin author for any reason, send an email to: jvpjoaopimentadev@gmail.com                </p>
            </body>
        </html>
                    """)

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return tectonicParametersCalc()
