# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingException, QgsGeometry, QgsFeature, QgsPointXY
import geopandas as gpd
from shapely.geometry import LineString, MultiLineString, Point
from shapely import wkt
import numpy as np
from ..parametersProcessing import (
    getStreamsInsideLayer,
    createGdfStream,
    obtainFirstAndLastPoint,
    createOrderColumn,
    fillOrder,
    mergeStreams,
    createGdfShape,
    selectStreamsInsideBasin,
    calculateStreamLength,
    longestDrainage
)

def verifyLibs():
    try:
        import geopandas
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import shapely
    except ImportError:
        raise QgsProcessingException('Shapely library not found, please install it and try again.')
    try:
        import numpy
    except ImportError:
        raise QgsProcessingException('Numpy library not found, please install it and try again.')

def calculateBasinLength(gdfStream,gdfShape,basin,feedback,useLongestRiver):
    if gdfStream.empty:
        gdfShape['Basin length (Lg) (km)'] = None
        return

    maxOrder = gdfStream['order'].max()
    filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]

    firstPoint = filterMaxOrder.iloc[-1]['last']
    lastPoint = filterMaxOrder.iloc[0]['first']

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfShape['Basin length (Lg) (km)'] = None
            return

        merged = MultiLineString(lines)

        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

        if mainRiver.geom_type == "LineString":

            firstPoint = tuple(mainRiver.coords[-1])
            lastPoint = tuple(mainRiver.coords[0])

        elif mainRiver.geom_type == "MultiLineString":

            firstLine = mainRiver.geoms[-1]
            lastLine = mainRiver.geoms[0]

            firstPoint = tuple(firstLine.coords[-1])
            lastPoint = tuple(lastLine.coords[0])

    dx = lastPoint[0] - firstPoint[0]
    dy = lastPoint[1] - firstPoint[1]

    minX, minY, maxX, maxY = gdfShape.total_bounds
    maxDimBasin = max(maxX - minX, maxY - minY)
    mult = maxDimBasin

    firstExtended = QgsPointXY(firstPoint[0] - dx * mult, firstPoint[1] - dy * mult)
    lastExtended = QgsPointXY(lastPoint[0] + dx * mult, lastPoint[1] + dy * mult)

    parallelLine = QgsGeometry.fromPolylineXY([firstExtended, lastExtended])
    intersection = parallelLine.intersection(QgsGeometry.fromWkt(gdfShape.boundary.iloc[0].wkt))

    if intersection.isEmpty():
        feedback.pushWarning('A parallel line between higher order channels does not intersect the perimeter of the basin of id'+str(basin.id())+', the drainage network has errors!')
        gdfShape['Basin length (Lg) (km)'] = None
        return

    pointsIntersection = intersection.asMultiPoint()
    pointsOrdered = sorted(pointsIntersection, key=lambda p: (p.y(), p.x()))

    basinLengthLine = QgsGeometry.fromPolylineXY([pointsOrdered[0], pointsOrdered[-1]])
    basinLength = basinLengthLine.length()
    basinLengthShapely = wkt.loads(basinLengthLine.asWkt())
    gdfShape['Basin length (Lg) (km)'] = basinLength/1000

    nPoints = 200
    fractions = np.linspace(0.05, 0.95, nPoints)
    points = [basinLengthShapely.interpolate(f, normalized=True) for f in fractions]

    allDistances = []
    allLines = []
    allPoints = []

    for point in points:
        eps = 0.001
        projectPt = basinLengthShapely.project(point)
        
        p1 = basinLengthShapely.interpolate(max(0, projectPt - eps))
        p2 = basinLengthShapely.interpolate(min(basinLengthShapely.length, projectPt + eps))
        
        dx = p2.x - p1.x
        dy = p2.y - p1.y
        
        nx = -dy
        ny = dx
        
        norm = np.sqrt(nx**2 + ny**2)
        if norm == 0:
            continue
        
        nx /= norm
        ny /= norm
        
        length = basinLengthShapely.length * 10000
        
        perpendicularLine = LineString([
            (point.x - nx * length, point.y - ny * length),
            (point.x + nx * length, point.y + ny * length)
        ])

        intersection = perpendicularLine.intersection(wkt.loads(gdfShape.boundary.iloc[0].wkt))

        intersectionPoints = []
        
        if not intersection.is_empty:
            if intersection.geom_type == "Point":
                intersectionPoints.append(intersection)
            elif intersection.geom_type == "MultiPoint":
                intersectionPoints.extend(list(intersection.geoms))

        intersectionPoints.sort(key=lambda p: point.distance(p))
        
        p1Intersect = intersectionPoints[0]
        p2Intersect = intersectionPoints[-1]
        
        distance = p1Intersect.distance(p2Intersect)
        
        fullLine = LineString([p1Intersect, p2Intersect])
        
        allDistances.append(distance)
        allLines.append(fullLine)
        allPoints.append(point)

    if allDistances:
        maxIdx = np.argmax(allDistances)
        maxDistance = allDistances[maxIdx]
        maxPoint = allPoints[maxIdx]
        maxLine = allLines[maxIdx]
    else:
        maxDistance = None
        maxPoint = None
        maxLine = None

    maxPerpendicularLength = maxDistance
    gdfShape['Basin width (Bw) (km)'] = maxPerpendicularLength/1000
    gdfShape['Basin shape (Bs) (km)'] = basinLength/maxPerpendicularLength

    dataWidth = {
        'geometry': [maxLine],
        'basin_id': [basin.id()],
        'basinLength': [basinLength],
        'basinWidth': [maxDistance],
        'length/width': [basinLength / maxDistance if maxDistance > 0 else None]
    }

    dataLength = {
        'geometry': [basinLengthShapely],
        'basin_id': [basin.id()],
        'basinLength': [basinLength],
        'basinWidth': [maxDistance],
        'length/width': [basinLength / maxDistance if maxDistance > 0 else None]
    }

    gdfWidth = gpd.GeoDataFrame(dataWidth, crs=gdfShape.crs)
    gdfLength = gpd.GeoDataFrame(dataLength, crs=gdfShape.crs)
    return gdfWidth, gdfLength

def createGeometryBasinLengthBasinWidth(drainageBasinLayer,streamLayer,feedback,useLongestRiver,basinLength,basinWidth):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfsLength = []
    gdfsWidth = []

    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside)
        if feedback.isCanceled():
            return
        gdfShape = createGdfShape(basin)
        gdfWidth, gdfLength  = calculateBasinLength(gdfStreamsInside, gdfShape, basin, feedback, useLongestRiver)
        gdfsLength.append(gdfLength)
        gdfsWidth.append(gdfWidth)
        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return
    gdfFinalLength = gpd.GeoDataFrame(
        gpd.pd.concat(gdfsLength, ignore_index=True),
        crs=gdfsLength[0].crs
    )
    gdfFinalWidth = gpd.GeoDataFrame(
        gpd.pd.concat(gdfsWidth, ignore_index=True),
        crs=gdfsWidth[0].crs
    )
    for _, row in gdfFinalLength.iterrows():

        feature = QgsFeature()

        feature.setGeometry(
            QgsGeometry.fromWkt(
                row.geometry.wkt
            )
        )

        feature.setAttributes([
            int(row["basin_id"]),
            float(row["basinLength"]),
            float(row["basinWidth"]),
            float(row["length/width"])
        ])

        basinLength.addFeature(feature)

    for _, row in gdfFinalWidth.iterrows():

        feature = QgsFeature()

        feature.setGeometry(
            QgsGeometry.fromWkt(
                row.geometry.wkt
            )
        )

        feature.setAttributes([
            int(row["basin_id"]),
            float(row["basinLength"]),
            float(row["basinWidth"]),
            float(row["length/width"])
        ])

        basinWidth.addFeature(feature)

    return