# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingException, QgsGeometry, QgsFeature
import geopandas as gpd
from shapely.geometry import LineString, MultiLineString, Point
from shapely.ops import unary_union, split
from ..parametersProcessing import (
    getStreamsInsideLayer,
    createGdfStream,
    obtainFirstAndLastPoint,
    createOrderColumn,
    fillOrder,
    mergeStreams,
    createGdfShape,
    selectStreamsInsideBasin,
    calculateStreamLength,
    longestDrainage,
    createGdfShape
)

def verifyLibs():
    try:
        import geopandas
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import shapely
    except ImportError:
        raise QgsProcessingException('Shapely library not found, please install it and try again.')

def assimetryIndex(gdfShape, gdfStreamsInside, useLongestRiver):
    maxOrder = gdfStreamsInside['order'].max()
    filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStreamsInside.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]

        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])
    lines = []
    basin = gdfShape.geometry.unary_union

    for geom in gdfStreamsInside.geometry:

        if geom.geom_type == "LineString":
            lines.append(geom)

        elif geom.geom_type == "MultiLineString":
            lines.extend(list(geom.geoms))

    mainRiver = filterMaxOrder.geometry.iloc[0]

    if mainRiver.geom_type == "LineString":

        coords = list(mainRiver.coords)

    else:

        segments = list(mainRiver.geoms)

        coords = list(segments[0].coords)

        for seg in segments[1:]:

            segCoords = list(seg.coords)

            if coords[-1] == segCoords[0]:
                coords.extend(segCoords[1:])
            else:
                coords.extend(segCoords)

        mainRiver = LineString(coords)

    coords = list(mainRiver.coords)

    startPoint = Point(coords[-1])
    endPoint = Point(coords[0])

    dxStart = coords[0][0] - coords[1][0]
    dyStart = coords[0][1] - coords[1][1]

    dxEnd = coords[-1][0] - coords[-2][0]
    dyEnd = coords[-1][1] - coords[-2][1]


    extensionLength = max(
        basin.bounds[2] - basin.bounds[0],
        basin.bounds[3] - basin.bounds[1]
    ) * 10


    coords = list(mainRiver.coords)

    coords.insert(
        0,
        (
            startPoint.x + dxStart * extensionLength,
            startPoint.y + dyStart * extensionLength
        )
    )

    coords.append(
        (
            endPoint.x + dxEnd * extensionLength,
            endPoint.y + dyEnd * extensionLength
        )
    )

    extendedRiver = LineString(coords)
    extendedRiver = extendedRiver.intersection(basin)

    dividedBasin = split(
        basin,
        extendedRiver
    )

    parts = list(dividedBasin.geoms)

    leftParts = []
    rightParts = []


    for polygon in parts:

        point = polygon.representative_point()


        distance = mainRiver.project(point)
        riverPoint = mainRiver.interpolate(distance)


        delta = 1


        if distance + delta <= mainRiver.length:
            nextPoint = mainRiver.interpolate(distance + delta)
        else:
            nextPoint = mainRiver.interpolate(distance - delta)


        flowVectorX = nextPoint.x - riverPoint.x
        flowVectorY = nextPoint.y - riverPoint.y


        vectorX = point.x - riverPoint.x
        vectorY = point.y - riverPoint.y


        crossProduct = (
            flowVectorX * vectorY -
            flowVectorY * vectorX
        )


        if crossProduct > 0:
            leftParts.append(polygon)

        else:
            rightParts.append(polygon)



    leftArea = unary_union(leftParts)
    rightArea = unary_union(rightParts)


    parts = [
        leftArea,
        rightArea
    ]

    if len(parts) != 2:
        return None

    riverCenterDistance = mainRiver.length / 2

    delta = min(
        1,
        mainRiver.length * 0.01
    )

    nextPoint = mainRiver.interpolate(
        min(mainRiver.length, riverCenterDistance + delta)
    )

    rightAreaNumber = None


    for polygon in parts:

        point = polygon.representative_point()

        distance = mainRiver.project(point)

        riverPoint = mainRiver.interpolate(
            distance
        )

        delta = 1

        if distance + delta <= mainRiver.length:

            nextPoint = mainRiver.interpolate(
                distance + delta
            )

        else:

            nextPoint = mainRiver.interpolate(
                distance - delta
            )

        flowVectorX = nextPoint.x - riverPoint.x
        flowVectorY = nextPoint.y - riverPoint.y

        vectorX = point.x - riverPoint.x
        vectorY = point.y - riverPoint.y

        crossProduct = (
            flowVectorX * vectorY -
            flowVectorY * vectorX
        )

        if crossProduct > 0:

            rightAreaNumber = polygon.area
            break


    if rightArea is None:
        return None

    asymmetryIndex = rightAreaNumber / basin.area

    gdfParts = gpd.GeoDataFrame(
        {
            "partId": range(len(parts)),
            "geometry": parts,
            "AF": asymmetryIndex,
            "area_right": rightAreaNumber,
            "area_total": basin.area
        },
        crs=gdfShape.crs
    )

    return gdfParts


def calculateBasinDivide(drainageBasinLayer, streamLayer, feedback, divideBasin, useLongestDrainage):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    streamsInside = getStreamsInsideLayer(
        streamLayer, drainageBasinLayer,
        feedback
    )

    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    basinsDivided = []

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        calculateStreamLength(gdfStreamsInside)
        gdf = assimetryIndex(gdfShape, gdfStreamsInside, useLongestDrainage)
        gdf["basin_id"] = int(basin.id())
        if feedback.isCanceled():
            return
        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')
        basinsDivided.append(gdf)
    gdfFinal = gpd.GeoDataFrame(
    gpd.pd.concat(basinsDivided, ignore_index=True),
    crs=basinsDivided[0].crs
    )
    for _, row in gdfFinal.iterrows():

        feature = QgsFeature()

        feature.setGeometry(
            QgsGeometry.fromWkt(
                row.geometry.wkt
            )
        )

        feature.setAttributes([
            int(row["basin_id"]),
            float(row["area_right"]),
            float(row["area_total"]),
            float(row["AF"])
        ])

        divideBasin.addFeature(feature)
    return
