# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from matplotlib import lines

from qgis.core import QgsPointXY, QgsRaster, QgsProcessingException, QgsGeometry, QgsFeature
import geopandas as gpd
from shapely.geometry import MultiLineString
import numpy as np
from shapely.ops import linemerge, substring
from ..parametersProcessing import (
    getStreamsInsideLayer,
    createGdfStream,
    obtainFirstAndLastPoint,
    createOrderColumn,
    fillOrder,
    mergeStreams,
    createGdfShape,
    selectStreamsInsideBasin,
    calculateStreamLength,
    longestDrainage,
    createGdfShape,
    createGdfTectonic)

def verifyLibs():
    try:
        import geopandas
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import shapely
    except ImportError:
        raise QgsProcessingException('Shapely library not found, please install it and try again.')
    try:
        import numpy
    except ImportError:
        raise QgsProcessingException('Shapely library not found, please install it and try again.')

def calculateSLindexMainChannel(gdfStream,dem,gdfTectonic,useLongestRiver, nSectionsSL):
    maxOrder = gdfStream['order'].max()
    filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfTectonic['Stream-length index mean (SLm)'] = None
            return

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

    nSections = nSectionsSL

    riverLength = filterMaxOrder.geometry.iloc[0].length
    sectionLength = riverLength / nSections

    sections = []
    river = filterMaxOrder.geometry.iloc[0]

    if river.geom_type == "MultiLineString":
        river = linemerge(river)

    if river.geom_type != "LineString":
        gdfTectonic['Stream-length index mean (SLm)'] = None
        return

    riverLength = river.length
    sectionLength = riverLength / nSections

    sections = []

    for i in range(nSections):

        startDistance = i * sectionLength
        endDistance = (i + 1) * sectionLength

        section = substring(
            river,
            startDistance,
            endDistance
        )

        sections.append(section)

    filterMaxOrder = gpd.GeoDataFrame(
        {
            'section': range(1, nSections + 1),
            'geometry': sections
        },
        crs=gdfStream.crs
    )
    filterMaxOrder['center'] = filterMaxOrder.geometry.interpolate(0.5, normalized=True)

    filterMaxOrder['length'] = filterMaxOrder.geometry.length

    filterMaxOrder['distance'] = (
        filterMaxOrder['length'].cumsum()
        - filterMaxOrder['length'] / 2
    )

    upstreamElevations = []
    downstreamElevations = []
    elevationDifferences = []

    for line in filterMaxOrder.geometry:

        upstreamPoint = line.interpolate(0, normalized=True)

        upstreamPointQgs = QgsPointXY(
            upstreamPoint.x,
            upstreamPoint.y
        )

        identificatorUpstream = dem.dataProvider().identify(
            upstreamPointQgs,
            QgsRaster.IdentifyFormat.IdentifyFormatValue
        )

        if identificatorUpstream.isValid():
            upstreamElevation = identificatorUpstream.results().get(1)
        else:
            upstreamElevation = None


        downstreamPoint = line.interpolate(1, normalized=True)

        downstreamPointQgs = QgsPointXY(
            downstreamPoint.x,
            downstreamPoint.y
        )

        identificatorDownstream = dem.dataProvider().identify(
            downstreamPointQgs,
            QgsRaster.IdentifyFormat.IdentifyFormatValue
        )

        if identificatorDownstream.isValid():
            downstreamElevation = identificatorDownstream.results().get(1)
        else:
            downstreamElevation = None

        if (
            upstreamElevation is not None
            and downstreamElevation is not None
        ):
            elevationDifference = (
                upstreamElevation - downstreamElevation
            )
        else:
            elevationDifference = None


        upstreamElevations.append(upstreamElevation)
        downstreamElevations.append(downstreamElevation)
        elevationDifferences.append(elevationDifference)


    filterMaxOrder['upstream_elevation'] = upstreamElevations
    filterMaxOrder['downstream_elevation'] = downstreamElevations
    filterMaxOrder['elevation_difference'] = elevationDifferences

    filterMaxOrder['SL'] = (
        (filterMaxOrder['elevation_difference']
        / filterMaxOrder['length'])
        * filterMaxOrder['distance']
    )
    filterMaxOrder['SLt'] = filterMaxOrder['elevation_difference'] / np.log(filterMaxOrder['distance'])

    filterMaxOrder['Stream-Length index mean (SLm)'] = None
    filterMaxOrder['Stream-Length index mean (SLm)'] = filterMaxOrder['SL'].mean()

    filterMaxOrder['Stream-Length index total (SLt)'] = None
    filterMaxOrder['Stream-Length index total (SLt)'] = filterMaxOrder['SLt'].mean()

    filterMaxOrder['Stream-Length index (SLm/SLt)'] = filterMaxOrder['Stream-Length index mean (SLm)']/filterMaxOrder['Stream-Length index total (SLt)']

    gdfSections = filterMaxOrder.copy()

    gdfPoints = filterMaxOrder.copy()
    gdfPoints['geometry'] = gdfPoints['center']
    gdfDistances = filterMaxOrder.copy()

    gdfDistances['geometry'] = [
        substring(
            river,
            0,
            distance
        )
        for distance in filterMaxOrder['distance']
    ]

    return gdfSections, gdfPoints, gdfDistances

def calculateSLindexGeometry(drainageBasinLayer,streamLayer,dem,feedback,useLongestRiver,SLsteps,SLcenterPoints,SLdistances,nSectionsSL):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)
    allSections = []
    allPoints = []
    allDistances = []
    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        calculateStreamLength(gdfStreamsInside)
        gdfTectonic = createGdfTectonic()
        gdfSections, gdfPoints, gdfDistances = calculateSLindexMainChannel(gdfStreamsInside,dem,gdfTectonic,useLongestRiver, nSectionsSL)

        if feedback.isCanceled():
            return

        gdfSections['basin_id'] = int(basin.id())
        gdfPoints['basin_id'] = int(basin.id())
        gdfDistances['basin_id'] = int(basin.id())
        allSections.append(gdfSections)
        allPoints.append(gdfPoints)
        allDistances.append(gdfDistances)
        if feedback.isCanceled():
            return
        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')
        if feedback.isCanceled():
            return

    gdfSections = gpd.pd.concat(allSections, ignore_index=True)
    gdfPoints = gpd.pd.concat(allPoints, ignore_index=True)
    gdfDistances = gpd.pd.concat(allDistances, ignore_index=True)

    for _, row in gdfSections.iterrows():

        feature = QgsFeature()

        feature.setGeometry(
            QgsGeometry.fromWkt(
                row.geometry.wkt
            )
        )

        feature.setAttributes([
            int(row["basin_id"]),
            float(row["section"]),
            float(row["length"]),
            float(row["distance"]),
            float(row["upstream_elevation"]),
            float(row["downstream_elevation"]),
            float(row["elevation_difference"]),
            float(row["SL"]),
            float(row["Stream-Length index mean (SLm)"]),
            float(row["SLt"]),
            float(row["Stream-Length index total (SLt)"]),
            float(row["Stream-Length index (SLm/SLt)"])
        ])

        SLsteps.addFeature(feature)

    for _, row in gdfPoints.iterrows():

        feature = QgsFeature()

        feature.setGeometry(
            QgsGeometry.fromWkt(
                row.geometry.wkt
            )
        )

        feature.setAttributes([
            int(row["basin_id"]),
            float(row["section"]),
            float(row["length"]),
            float(row["distance"]),
            float(row["upstream_elevation"]),
            float(row["downstream_elevation"]),
            float(row["elevation_difference"]),
            float(row["SL"]),
            float(row["Stream-Length index mean (SLm)"]),
            float(row["SLt"]),
            float(row["Stream-Length index total (SLt)"]),
            float(row["Stream-Length index (SLm/SLt)"])
        ])

        SLcenterPoints.addFeature(feature)

    for _, row in gdfDistances.iterrows():

        feature = QgsFeature()

        feature.setGeometry(
            QgsGeometry.fromWkt(
                row.geometry.wkt
            )
        )

        feature.setAttributes([
            int(row["basin_id"]),
            float(row["section"]),
            float(row["length"]),
            float(row["distance"]),
            float(row["upstream_elevation"]),
            float(row["downstream_elevation"]),
            float(row["elevation_difference"]),
            float(row["SL"]),
            float(row["Stream-Length index mean (SLm)"]),
            float(row["SLt"]),
            float(row["Stream-Length index total (SLt)"]),
            float(row["Stream-Length index (SLm/SLt)"])
        ])

        SLdistances.addFeature(feature)
    return

