# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsPointXY, QgsProcessingException, QgsGeometry, QgsFeature
import geopandas as gpd
from shapely.geometry import LineString, MultiLineString
from ..parametersProcessing import (
    getStreamsInsideLayer,
    createGdfStream,
    obtainFirstAndLastPoint,
    createOrderColumn,
    fillOrder,
    mergeStreams,
    createGdfShape,
    selectStreamsInsideBasin,
    calculateStreamLength,
    longestDrainage,
    createGdfShape)

def verifyLibs():
    try:
        import geopandas
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import shapely
    except ImportError:
        raise QgsProcessingException('Shapely library not found, please install it and try again.')

def calculateSinuosityIndex(gdfStream,useLongestRiver, precisionSnapCoordinates, gdfShape):
    maxOrder = gdfStream['order'].max()
    filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]

    firstPoint = filterMaxOrder.iloc[-1]['last']
    lastPoint = filterMaxOrder.iloc[0]['first']

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        merged = MultiLineString(lines)

        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last']),
            precisionSnapCoordinates
        )

        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

        if mainRiver.geom_type == "LineString":

            firstPoint = tuple(mainRiver.coords[-1])
            lastPoint = tuple(mainRiver.coords[0])

        elif mainRiver.geom_type == "MultiLineString":

            firstLine = mainRiver.geoms[-1]
            lastLine = mainRiver.geoms[0]

            firstPoint = tuple(firstLine.coords[-1])
            lastPoint = tuple(lastLine.coords[0])

    straightLine = LineString([
        QgsPointXY(firstPoint[0], firstPoint[1]),
        QgsPointXY(lastPoint[0], lastPoint[1])
    ])
    lengthStraightLine = straightLine.length
    lengthStream = filterMaxOrder.geometry.length.sum()
    sinuosity = lengthStream / lengthStraightLine
    return straightLine, lengthStraightLine, lengthStream, sinuosity

def calculateSinuosityGeometry(drainageBasinLayer,streamLayer,feedback,precisionSnapCoordinates,minimumChannelLength,useLongestRiver,straightLinesSink):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback, precisionSnapCoordinates)
    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)
    straightLines = []
    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape)
        calculateStreamLength(gdfStreamsInside,minimumChannelLength)
        straightLine, lengthStraightLine, lengthStream, sinuosity = calculateSinuosityIndex(gdfStreamsInside,useLongestRiver, precisionSnapCoordinates, gdfShape)
        if feedback.isCanceled():
            return
        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')
        straightLines.append({
            "basin_id": int(basin.id()),
            "geometry": straightLine,
            "length_straight_line": lengthStraightLine,
            "length_stream": lengthStream,
            "sinuosity": sinuosity
        })
    print(type(straightLines))
    if feedback.isCanceled():
        return
    gdfStraightLines = gpd.GeoDataFrame(
        straightLines,
        geometry="geometry",
        crs=gdfShape.crs
    )

    for _, row in gdfStraightLines.iterrows():

        feature = QgsFeature()

        feature.setGeometry(
            QgsGeometry.fromWkt(
                row.geometry.wkt
            )
        )

        feature.setAttributes([
            int(row["basin_id"]),
            float(row["length_stream"]),
            float(row["length_straight_line"]),
            float(row["sinuosity"])
        ])

        straightLinesSink.addFeature(feature)
    return

    return

