# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsPointXY, QgsRaster, QgsProcessingException, QgsGeometry, QgsFeature
import geopandas as gpd
from osgeo import gdal
from shapely.geometry import LineString, MultiLineString
import numpy as np
from ..parametersProcessing import (
    getStreamsInsideLayer,
    createGdfStream,
    obtainFirstAndLastPoint,
    createOrderColumn,
    fillOrder,
    mergeStreams,
    createGdfShape,
    selectStreamsInsideBasin,
    calculateStreamLength,
    longestDrainage
)

def verifyLibs():
    try:
        import geopandas
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import shapely
    except ImportError:
        raise QgsProcessingException('Shapely library not found, please install it and try again.')
    try:
        import numpy
    except ImportError:
        raise QgsProcessingException('Numpy library not found, please install it and try again.')

def valleyFloorWidthHeight(gdfStreamsInside, gdfShape, nPoints, dem, limitForValleyFloor, minForValleyHeight, useLongestRiver, limitDescendValley):

    maxOrder = gdfStreamsInside["order"].max()
    filterMaxOrder = gdfStreamsInside[gdfStreamsInside["order"] == maxOrder]

    mainRiver = filterMaxOrder.geometry.iloc[0]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStreamsInside.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

    boundary = gdfShape.geometry.unary_union

    fractions = np.linspace(
        0.1,
        0.9,
        nPoints
    )

    points = [
        mainRiver.interpolate(
            fraction,
            normalized=True
        )
        for fraction in fractions
    ]

    transverseLines = []

    for i, point in enumerate(points):

        eps = 0.001

        p1 = mainRiver.interpolate(
            max(
                0,
                mainRiver.project(point) - eps
            )
        )

        p2 = mainRiver.interpolate(
            min(
                mainRiver.length,
                mainRiver.project(point) + eps
            )
        )

        dx = p2.x - p1.x
        dy = p2.y - p1.y

        nx = -dy
        ny = dx

        norm = np.sqrt(nx ** 2 + ny ** 2)

        if norm == 0:
            continue

        nx /= norm
        ny /= norm

        length = max(
            boundary.bounds[2] - boundary.bounds[0],
            boundary.bounds[3] - boundary.bounds[1]
        ) * 2

        line = LineString([
            (
                point.x - nx * length,
                point.y - ny * length
            ),
            (
                point.x + nx * length,
                point.y + ny * length
            )
        ])

        clipped = line.intersection(boundary)

        if clipped.is_empty:
            continue

        if clipped.geom_type == "LineString":

            transverseLines.append({
                "id": i + 1,
                "geometry": clipped
            })

        elif clipped.geom_type == "MultiLineString":

            largest = max(
                clipped.geoms,
                key=lambda geom: geom.length
            )

            transverseLines.append({
                "id": i + 1,
                "geometry": largest
            })

    gdf = gpd.GeoDataFrame(
        transverseLines,
        crs=gdfShape.crs
    )

    provider = dem.dataProvider()

    gdf["profile"] = None
    gdf["river_point"] = None
    gdf["river_elevation"] = None
    gdf["left_point"] = None
    gdf["left_elevation"] = None
    gdf["right_point"] = None
    gdf["right_elevation"] = None
    gdf["left_1m_point"] = None
    gdf["left_1m_elevation"] = None
    gdf["right_1m_point"] = None
    gdf["right_1m_elevation"] = None
    gdf["width_1m"] = None
    gdf["lowest_point"] = None
    gdf["lowest_elevation"] = None
    gdf["vf_ratio"] = None
    validIndexes = []
    for idx, row in gdf.iterrows():

        line = row.geometry

        profile = []

        distance = 0

        while distance <= line.length:

            samplePoint = line.interpolate(distance)

            pointQgs = QgsPointXY(
                samplePoint.x,
                samplePoint.y
            )

            identify = provider.identify(
                pointQgs,
                QgsRaster.IdentifyFormat.IdentifyFormatValue
            )

            if identify.isValid():

                value = identify.results().get(1)

                if value is not None:

                    profile.append({
                        "point": samplePoint,
                        "distance": distance,
                        "elevation": value
                    })

            distance += 1

        if len(profile) < 3:
            continue

        intersection = line.intersection(mainRiver)

        if intersection.is_empty:
            continue

        if intersection.geom_type == "MultiPoint":
            intersection = list(intersection.geoms)[0]

        pointQgs = QgsPointXY(
            intersection.x,
            intersection.y
        )

        identify = provider.identify(
            pointQgs,
            QgsRaster.IdentifyFormat.IdentifyFormatValue
        )

        if identify.isValid():
            riverElevation = identify.results().get(1)
        else:
            riverElevation = None

        gdf.at[idx, "river_point"] = intersection
        gdf.at[idx, "river_elevation"] = riverElevation

        profile.append({
            "point": intersection,
            "distance": line.project(intersection),
            "elevation": riverElevation
        })

        profile.sort(key=lambda p: p["distance"])

        riverIndex = next(
            i for i, p in enumerate(profile)
            if p["point"].equals(intersection)
        )

        leftIndex = riverIndex

        while leftIndex > 0:

            diff = profile[leftIndex - 1]["elevation"] - profile[leftIndex]["elevation"]

            if diff >= -(limitDescendValley):
                leftIndex -= 1
            else:
                break

        rightIndex = riverIndex

        while rightIndex < len(profile) - 1:

            diff = profile[rightIndex + 1]["elevation"] - profile[rightIndex]["elevation"]

            if diff >= -(limitDescendValley):
                rightIndex += 1
            else:
                break


        leftOneMeter = riverIndex

        for i in range(riverIndex - 1, leftIndex - 1, -1):
            diff = profile[i]["elevation"] - riverElevation

            if diff < limitForValleyFloor:
                leftOneMeter = i
            else:
                break

        rightOneMeter = riverIndex

        for i in range(riverIndex + 1, rightIndex + 1):
            diff = profile[i]["elevation"] - riverElevation

            if diff < limitForValleyFloor:
                rightOneMeter = i
            else:
                break

        if leftOneMeter is not None:
            gdf.at[idx, "left_1m_point"] = profile[leftOneMeter]["point"]
            gdf.at[idx, "left_1m_elevation"] = profile[leftOneMeter]["elevation"]

        if rightOneMeter is not None:
            gdf.at[idx, "right_1m_point"] = profile[rightOneMeter]["point"]
            gdf.at[idx, "right_1m_elevation"] = profile[rightOneMeter]["elevation"]

        if leftOneMeter is not None and rightOneMeter is not None:
            gdf.at[idx, "width_1m"] = (
                profile[leftOneMeter]["point"].distance(
                    profile[rightOneMeter]["point"]
                )
            )

        gdf.at[idx, "left_point"] = profile[leftIndex]["point"]
        gdf.at[idx, "left_elevation"] = profile[leftIndex]["elevation"]

        gdf.at[idx, "right_point"] = profile[rightIndex]["point"]
        gdf.at[idx, "right_elevation"] = profile[rightIndex]["elevation"]

        gdf.at[idx, "profile"] = profile

        start = min(leftIndex, rightIndex)
        end = max(leftIndex, rightIndex)

        lowestIndex = min(
            range(start, end + 1),
            key=lambda i: profile[i]["elevation"]
        )

        gdf.at[idx, "lowest_point"] = profile[lowestIndex]["point"]
        gdf.at[idx, "lowest_elevation"] = profile[lowestIndex]["elevation"]

        leftDiff = profile[leftIndex]["elevation"] - profile[lowestIndex]["elevation"]
        rightDiff = profile[rightIndex]["elevation"] - profile[lowestIndex]["elevation"]

        minRelief = minForValleyHeight
        if leftDiff == 0 or rightDiff == 0:
            continue

        if leftDiff < minRelief or rightDiff < minRelief:
            continue

        denominator = leftDiff + rightDiff

        gdf.at[idx, "vf_ratio"] = (
            2 * gdf.at[idx, "width_1m"] / denominator
        )
        validIndexes.append(idx)
    vf_ratio_m = gdf.loc[validIndexes, "vf_ratio"].mean()
    gdf["vf_ratio_m"] = vf_ratio_m

    gdf = gdf.loc[validIndexes].reset_index(drop=True)
    limits = []
    oneMeter = []

    for _, row in gdf.iterrows():

        if row["left_point"] is not None and row["right_point"] is not None:

            limits.append({
                "id": row["id"],
                "geometry": LineString([
                    row["left_point"],
                    row["right_point"]
                ]),
                "left_elevation": row["left_elevation"],
                "right_elevation": row["right_elevation"],
                "lowest_elevation": row["lowest_elevation"],
                "width_1m": row["width_1m"],
                "vf_ratio": row["vf_ratio"],
                "vf_ratio_m": row["vf_ratio_m"]
            })

        if row["left_1m_point"] is not None and row["right_1m_point"] is not None:

            oneMeter.append({
                "id": row["id"],
                "geometry": LineString([
                    row["left_1m_point"],
                    row["right_1m_point"]
                ]),
                "left_elevation": row["left_elevation"],
                "right_elevation": row["right_elevation"],
                "lowest_elevation": row["lowest_elevation"],
                "width_1m": row["width_1m"],
                "vf_ratio": row["vf_ratio"],
                "vf_ratio_m": row["vf_ratio_m"]
            })

    gdfLimits = gpd.GeoDataFrame(
        limits,
        crs=gdf.crs
    )

    gdf1m = gpd.GeoDataFrame(
        oneMeter,
        crs=gdf.crs
    )

    return gdfLimits, gdf1m

def loadDEM(demLayer):
    DEMpath = demLayer.dataProvider().dataSourceUri().split('|')[0]
    ds = gdal.Open(DEMpath)
    band = ds.GetRasterBand(1)
    demArray = band.ReadAsArray()
    noData = band.GetNoDataValue() if band.GetNoDataValue() is not None else -9999
    gt = ds.GetGeoTransform()
    proj = ds.GetProjection()
    rows, cols = demArray.shape
    ds = None
    return demArray, noData, gt, proj, rows, cols

def calculateVfVh(drainageBasinLayer, streamLayer, feedback, sinkLimits, sink1m, demLayer, nPoints, limitForValleyFloor, minForValleyHeight, useLongestDrainage, limitDescendValley):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    streamsInside = getStreamsInsideLayer(
        streamLayer, drainageBasinLayer,
        feedback
    )

    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    gdfsLimits = []
    gdfs1m = []

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        calculateStreamLength(gdfStreamsInside)

        gdfLimits, gdf1m = valleyFloorWidthHeight(gdfStreamsInside, gdfShape, nPoints, demLayer, limitForValleyFloor, minForValleyHeight, useLongestDrainage, limitDescendValley)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')
        gdfLimits["basin_id"] = int(basin.id())
        gdf1m["basin_id"] = int(basin.id())
        gdfsLimits.append(gdfLimits)
        gdfs1m.append(gdf1m)
    if gdfsLimits:

        gdfFinalLimits = gpd.GeoDataFrame(
            gpd.pd.concat(
                gdfsLimits,
                ignore_index=True
            ),
            crs=gdfsLimits[0].crs
        )

        for _, row in gdfFinalLimits.iterrows():

            feature = QgsFeature()

            feature.setGeometry(
                QgsGeometry.fromWkt(
                    row.geometry.wkt
                )
            )

            feature.setAttributes([
                int(row["basin_id"]),
                float(row["left_elevation"]),
                float(row["right_elevation"]),
                float(row["lowest_elevation"]),
                float(row["width_1m"]),
                float(row["vf_ratio"]),
                float(row["vf_ratio_m"])
            ])

            sinkLimits.addFeature(feature)

    if gdfs1m:

        gdfFinal1m = gpd.GeoDataFrame(
            gpd.pd.concat(
                gdfs1m,
                ignore_index=True
            ),
            crs=gdfs1m[0].crs
        )

        for _, row in gdfFinal1m.iterrows():

            feature = QgsFeature()

            feature.setGeometry(
                QgsGeometry.fromWkt(
                    row.geometry.wkt
                )
            )

            feature.setAttributes([
                int(row["basin_id"]),
                float(row["left_elevation"]),
                float(row["right_elevation"]),
                float(row["lowest_elevation"]),
                float(row["width_1m"]),
                float(row["vf_ratio"]),
                float(row["vf_ratio_m"])
            ])

            sink1m.addFeature(feature)
    return
