# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from matplotlib import lines

from qgis.core import QgsPointXY, QgsRaster, QgsProcessingException, QgsGeometry, QgsWkbTypes
import geopandas as gpd
from osgeo import gdal, ogr
from scipy.spatial import Voronoi
import math
from shapely.geometry import LineString, MultiLineString, Point, GeometryCollection
from shapely import intersection, wkt
import numpy as np
from shapely.ops import unary_union, linemerge, split, snap, substring

def verifyLibs():
    try:
        import geopandas
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import scipy
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import shapely
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import numpy
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
def getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback):
    streamsWithinLayer = []

    streamShapes = [
        wkt.loads(stream.geometry().asWkt())
        for stream in streamLayer.getFeatures()
    ]
    streamsUnion = unary_union(streamShapes)

    basinShapes = [
        wkt.loads(basin.geometry().asWkt())
        for basin in drainageBasinLayer.getFeatures()
    ]
    basinUnion = unary_union(basinShapes)
    intersection = streamsUnion.intersection(basinUnion)

    if intersection.geom_type == "GeometryCollection":

        for geom in intersection.geoms:
            if geom.geom_type in ("LineString", "MultiLineString"):
                snappedGeom = QgsGeometry.fromWkt(geom.wkt)
                streamsWithinLayer.append(snappedGeom)

    elif intersection.geom_type in ("LineString", "MultiLineString"):
        geoms = intersection.geoms if intersection.geom_type == "MultiLineString" else [intersection]
        
        for geom in geoms:
            snappedGeom = QgsGeometry.fromWkt(geom.wkt)
            streamsWithinLayer.append(snappedGeom)

    return streamsWithinLayer
def toSingleLine(geom):
    if geom.geom_type == "LineString":
        return geom
    if geom.geom_type == "MultiLineString":
        all_coords = []
        for part in geom.geoms:
            all_coords.extend(list(part.coords))
        return LineString(all_coords)
    return geom
def filterIsolatedLines(gdf):
    if len(gdf) <= 1:
        return gdf.iloc[0:0]
    
    sindex = gdf.sindex
    keepIndices = []
    
    for idx, row in gdf.iterrows():
        geom = row.geometry
        possibleMatchesIdx = list(sindex.intersection(geom.bounds))
        possibleMatchesIdx = [i for i in possibleMatchesIdx if i != idx]
        
        touchesAny = False
        for neighborIdx in possibleMatchesIdx:
            neighborGeom = gdf.iloc[neighborIdx].geometry
            if geom.touches(neighborGeom):
                touchesAny = True
                break
            elif geom.intersects(neighborGeom) and not geom.equals(neighborGeom):
                intersection = geom.intersection(neighborGeom)
                if intersection.geom_type in ['Point', 'MultiPoint']:
                    touchesAny = True
                    break
                elif intersection.geom_type == 'LineString' and intersection.length == 0:
                    touchesAny = True
                    break
        
        if touchesAny:
            keepIndices.append(idx)
    
    return gdf.loc[keepIndices]

def selectStreamsInsideBasin(streamGdf, drainageBasinGdf, basin, feedback, streams):
    linesInBasins = gpd.overlay(streamGdf, drainageBasinGdf, how="intersection", keep_geom_type=True)
    linesInBasins = linesInBasins[
        linesInBasins.geometry.geom_type.isin(["LineString", "MultiLineString"])
    ]
    if streams is False:
        if linesInBasins.empty:
            feedback.pushWarning(
                'There are no mountain fronts entirely within the basin of id '
                + str(basin.id())
                + ' and the calculation of some parameters for this basin may be compromised'
            )
            return linesInBasins
    if streams is True:
        if linesInBasins.empty:
            feedback.pushWarning(
                'There are no channels entirely within the basin of id '
                + str(basin.id())
                + ' and the calculation of some parameters for this basin may be compromised'
            )
            return linesInBasins

    linesInBasins.geometry = linesInBasins.geometry.apply(toSingleLine)
    if streams is True:
        linesInBasins = filterIsolatedLines(linesInBasins)

    coords = linesInBasins.geometry.apply(
        lambda geom: [geom.coords[0], geom.coords[-1]]
    )

    linesInBasins["first"] = coords.str[0]
    linesInBasins["last"]  = coords.str[1]

    return linesInBasins
def createGdfStream(streams):
    geometries2d = []

    for feat in streams:
        if feat.constGet() is None:
            continue
        if feat.constGet().is3D():
            feat.get().dropZValue()
        if feat.constGet().isMeasure():
            feat.get().dropMValue()

        if not feat.isMultipart():
            geomType = feat.wkbType()
            if QgsWkbTypes.geometryType(geomType) != QgsWkbTypes.GeometryType.PointGeometry:
                geometries2d.append(feat)

        else:
            multiGeom = feat.asGeometryCollection()
            for part in multiGeom:
                geomType = part.wkbType()
                if QgsWkbTypes.geometryType(geomType) != QgsWkbTypes.GeometryType.PointGeometry:
                    geometries2d.append(part)

    gdfStream = gpd.GeoDataFrame(
        geometry=geometries2d
    )
    return gdfStream
def obtainFirstAndLastPoint(gdfStream):
    if gdfStream.empty:
        return
    coords = gdfStream.geometry.apply(lambda geom: [geom.coords[0], geom.coords[-1]])
    gdfStream['first'] = coords.str[0]
    gdfStream['last'] = coords.str[1]

    return

def createOrderColumn(gdfStream):
    gdfStream['order'] = None
    return

def findOrder(gdf, streamMap, index):
    if gdf.at[index, 'order'] is not None:
        return

    stream = gdf.loc[index]
    first = str(stream['first'])

    if first not in streamMap:
        gdf.at[index, 'order'] = 1
        return

    tributariesIndexes = streamMap[first]
    maxOrder = 1
    maxOrderCount = 0

    for tributaryIndex in tributariesIndexes:
        if gdf.at[tributaryIndex, 'order'] is None:
            try:
                findOrder(gdf, streamMap, tributaryIndex)
            except RecursionError:
                raise QgsProcessingException('The channels are forming a loop, making it impossible to classify the channels (check that the channel coordinate precision is not causing the channels to merge and form a loop).')

        tributary_order = gdf.at[tributaryIndex, 'order']

        if maxOrder == tributary_order:
            maxOrderCount += 1
        elif maxOrder < tributary_order:
            maxOrder = tributary_order
            maxOrderCount = 1

    gdf.at[index, 'order'] = maxOrder + 1 if maxOrderCount > 1 else maxOrder

def createStreamMap(gdfStream):
    streamMap = {}
    for index, row in gdfStream.iterrows():
        last = str(row['last'])

        if last not in streamMap:
            streamMap[last] = []

        streamMap[last].append(index)
    return streamMap

def fillOrder(gdfStream):
    gdfStream['order'] = None
    streamMap = createStreamMap(gdfStream)

    for index in gdfStream.index:
        findOrder(gdfStream, streamMap, index)

def mergeStreams(gdf):
    if gdf.empty:
        return

    gdf['processed'] = False
    newRows = []
    indicesToRemove = []

    for idx in gdf.index:
        if gdf.loc[idx, 'processed']:
            continue

        currentIdx = idx
        chain = [currentIdx]
        gdf.loc[currentIdx, 'processed'] = True
        currentOrder = gdf.loc[currentIdx, 'order']

        while True:
            currentStart = gdf.loc[currentIdx, 'first']
            candidates = gdf[
                (gdf['last'] == currentStart) & 
                (gdf['order'] == currentOrder) & 
                (~gdf['processed'])
            ]

            if len(candidates) != 1:
                break

            nextIdx = candidates.index[0]
            chain.insert(0, nextIdx)
            gdf.loc[nextIdx, 'processed'] = True
            currentIdx = nextIdx

        currentIdx = idx

        while True:
            currentEnd = gdf.loc[currentIdx, 'last']
            candidates = gdf[
                (gdf['first'] == currentEnd) &
                (gdf['order'] == currentOrder) &
                (~gdf['processed'])
            ]

            if len(candidates) != 1:
                break

            nextIdx = candidates.index[0]
            chain.append(nextIdx)
            gdf.loc[nextIdx, 'processed'] = True
            currentIdx = nextIdx

        if len(chain) > 1:
            geoms = gdf.loc[chain, 'geometry'].tolist()

            allCoords = []
            for i, geom in enumerate(geoms):
                if i == 0:
                    allCoords.extend(geom.coords[:])
                else:
                    allCoords.extend(geom.coords[1:])
            
            newGeom = geoms[0].__class__(allCoords)
            
            newRows.append({
                'geometry': newGeom,
                'first': allCoords[0],
                'last': allCoords[-1],
                'order': currentOrder
            })
            
            indicesToRemove.extend(chain)

    gdf.drop(indicesToRemove, inplace=True)
    
    for row in newRows:
        newIndex = gdf.index.max() + 1 if not gdf.empty else 0
        gdf.loc[newIndex] = row
    
    gdf.drop(columns=['processed'], inplace=True, errors='ignore')
    
    if not gdf.index.is_unique:
        gdf.reset_index(drop=True, inplace=True)
    return

def calculateStreamLength(gdfStream):

    gdfStream['length'] = gdfStream.geometry.length
    return

def createGdfLinear(gdfStream):
    if gdfStream.empty:
        gdfLinear = gpd.GeoDataFrame({'Stream Order': [1]})
        gdfLinear.loc[len(gdfLinear)] = [None]
        return gdfLinear

    maxStreamOrder = gdfStream['order'].max()
    gdfLinear = gpd.GeoDataFrame({'Stream Order': range(1, maxStreamOrder + 1)})
    gdfLinear.loc[len(gdfLinear)] = [None]
    return gdfLinear

def calculateStreamNumber (gdfStream,gdfLinear):
    streamNumber = gdfStream['order'].value_counts().sort_index()
    gdfLinear['Stream number'] = gdfLinear['Stream Order'].map(streamNumber)
    return

def calculateTotalStreamLength(gdfStream,gdfLinear):
    gdfWithSumLength = gdfStream.groupby('order')['length'].sum()
    gdfLinear['Stream length total (km)'] = gdfLinear['Stream Order'].map(gdfWithSumLength)/1000
    return

def calculateMeanStreamLength(gdfStream,gdfLinear):
    gdfWithMeansLenghts = gdfStream.groupby('order')['length'].mean()
    gdfLinear['Stream length mean (km)'] = gdfLinear['Stream Order'].map(gdfWithMeansLenghts)/1000
    return

def calculateStreamLengthRatio (gdfLinear):
    lengthGroupedByOrder = gdfLinear.set_index('Stream Order')['Stream length mean (km)']
    streamLengthRatio = (lengthGroupedByOrder / lengthGroupedByOrder.shift(+1))
    gdfLinear['Stream length ratio'] = gdfLinear['Stream Order'].map(streamLengthRatio)
    return

def calculateStreamLengthRatioMean (gdfLinear):
    streamLengthRatioMean = gdfLinear['Stream length ratio'].mean()
    gdfLinear.loc[gdfLinear.index[-1], 'Mean stream length ratio'] = streamLengthRatioMean
    return

def calculateBifurcationRatio (gdfLinear):
    streamNumber = gdfLinear.set_index('Stream Order')['Stream number']
    bifurcationRatio = streamNumber/streamNumber.shift(-1)
    gdfLinear['Bifurcation ratio'] = gdfLinear['Stream Order'].map(bifurcationRatio)
    return

def calculateBifurcationRatioMean (gdfLinear):
    bifurcationRatioMean = gdfLinear['Bifurcation ratio'].mean()
    gdfLinear.loc[gdfLinear.index[-1], 'Mean bifurcation ratio'] = bifurcationRatioMean
    return

def calculateRhoCoefficient (gdfLinear):
    Rlm = gdfLinear['Stream length ratio'].mean()
    Rbm = gdfLinear['Bifurcation ratio'].mean()

    RhoCoefficient = Rlm/Rbm
    gdfLinear.loc[gdfLinear.index[-1], 'RHO coefficient'] = RhoCoefficient
    return

def calculateSinuosityIndex(gdfStream,gdfLinear,useLongestRiver):
    if gdfStream.empty:
        gdfLinear['Main channel sinuosity index'] = None
        return

    maxOrder = gdfStream['order'].max()
    filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]

    firstPoint = filterMaxOrder.iloc[-1]['last']
    lastPoint = filterMaxOrder.iloc[0]['first']
    totalLength = gdfLinear.loc[gdfLinear['Stream Order'] == maxOrder, 'Stream length total (km)'].values[0]
    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfLinear['Main channel sinuosity index'] = None
            return

        merged = MultiLineString(lines)

        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )

        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

        if mainRiver.geom_type == "LineString":

            firstPoint = tuple(mainRiver.coords[-1])
            lastPoint = tuple(mainRiver.coords[0])

        elif mainRiver.geom_type == "MultiLineString":

            firstLine = mainRiver.geoms[-1]
            lastLine = mainRiver.geoms[0]

            firstPoint = tuple(firstLine.coords[-1])
            lastPoint = tuple(lastLine.coords[0])

        totalLength = filterMaxOrder.geometry.length.iloc[0]/1000

    straightLine = QgsGeometry.fromPolylineXY([
        QgsPointXY(firstPoint[0], firstPoint[1]),
        QgsPointXY(lastPoint[0], lastPoint[1])
    ])

    straightLineLength = straightLine.length()/1000

    
    sinuosityIndex = totalLength/straightLineLength
    gdfLinear.loc[gdfLinear.index[-1], 'Main channel sinuosity index'] = sinuosityIndex
    return

def createGdfShape(basin):
    basinGeom = basin.geometry()
    gdfShape = gpd.GeoDataFrame(geometry=[basinGeom])
    return gdfShape

def calculateAreaPerimeter(gdfShape):
    gdfShape['Area (km2)'] = [gdfShape.geometry.area/1000000]
    gdfShape['Perimeter (km)'] = [gdfShape.geometry.length/1000]
    return

def calculateFitnessRatio(gdfShape,gdfLinear,gdfStream,useLongestRiver):
    maxOrder = gdfLinear['Stream Order'].max()
    totalLength = gdfLinear.loc[gdfLinear['Stream Order'] == maxOrder, 'Stream length total (km)'].values[0]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfLinear['Fitness ratio (Rf)'] = None
            return

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])
        totalLength = (filterMaxOrder.geometry.iloc[0].length)/1000

    fitnessRatio = (totalLength/gdfShape['Perimeter (km)'])
    gdfLinear.loc[gdfLinear.index[-1], 'Fitness ratio (Rf)'] = fitnessRatio.iloc[0][0]
    return

def calculateBasinLength(gdfStream,gdfShape,basin,feedback,useLongestRiver,gdfTectonic,tectonic,nPoints):
    if gdfStream.empty:
        gdfShape['Basin length (Bl) (km)'] = None
        return

    maxOrder = gdfStream['order'].max()
    filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]

    firstPoint = filterMaxOrder.iloc[-1]['last']
    lastPoint = filterMaxOrder.iloc[0]['first']

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfShape['Basin length (Bl) (km)'] = None
            return

        merged = MultiLineString(lines)

        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

        if mainRiver.geom_type == "LineString":

            firstPoint = tuple(mainRiver.coords[-1])
            lastPoint = tuple(mainRiver.coords[0])

        elif mainRiver.geom_type == "MultiLineString":

            firstLine = mainRiver.geoms[-1]
            lastLine = mainRiver.geoms[0]

            firstPoint = tuple(firstLine.coords[-1])
            lastPoint = tuple(lastLine.coords[0])

    dx = lastPoint[0] - firstPoint[0]
    dy = lastPoint[1] - firstPoint[1]

    minX, minY, maxX, maxY = gdfShape.total_bounds
    maxDimBasin = max(maxX - minX, maxY - minY)
    mult = maxDimBasin

    firstExtended = QgsPointXY(firstPoint[0] - dx * mult, firstPoint[1] - dy * mult)
    lastExtended = QgsPointXY(lastPoint[0] + dx * mult, lastPoint[1] + dy * mult)

    parallelLine = QgsGeometry.fromPolylineXY([firstExtended, lastExtended])
    intersection = parallelLine.intersection(QgsGeometry.fromWkt(gdfShape.boundary.iloc[0].wkt))

    if intersection.isEmpty():
        feedback.pushWarning('A parallel line between higher order channels does not intersect the perimeter of the basin of id'+str(basin.id())+', the drainage network has errors!')
        gdfShape['Basin length (Bl) (km)'] = None
        return

    pointsIntersection = intersection.asMultiPoint()
    pointsOrdered = sorted(pointsIntersection, key=lambda p: (p.y(), p.x()))

    basinLengthLine = QgsGeometry.fromPolylineXY([pointsOrdered[0], pointsOrdered[-1]])
    basinLength = basinLengthLine.length()
    basinLengthShapely = wkt.loads(basinLengthLine.asWkt())
    gdfShape['Basin length (Bl) (km)'] = basinLength/1000

    if nPoints is None:
        return

    fractions = np.linspace(0.05, 0.95, nPoints)
    points = [basinLengthShapely.interpolate(f, normalized=True) for f in fractions]

    allDistances = []
    allLines = []
    allPoints = []

    for point in points:
        eps = 0.001
        projectPt = basinLengthShapely.project(point)
        
        p1 = basinLengthShapely.interpolate(max(0, projectPt - eps))
        p2 = basinLengthShapely.interpolate(min(basinLengthShapely.length, projectPt + eps))
        
        dx = p2.x - p1.x
        dy = p2.y - p1.y
        
        nx = -dy
        ny = dx
        
        norm = np.sqrt(nx**2 + ny**2)
        if norm == 0:
            continue
        
        nx /= norm
        ny /= norm
        
        length = basinLengthShapely.length * 10000
        
        perpendicularLine = LineString([
            (point.x - nx * length, point.y - ny * length),
            (point.x + nx * length, point.y + ny * length)
        ])
        
        intersection = perpendicularLine.intersection(wkt.loads(gdfShape.boundary.iloc[0].wkt))

        intersectionPoints = []
        
        if not intersection.is_empty:
            if intersection.geom_type == "Point":
                intersectionPoints.append(intersection)
            elif intersection.geom_type == "MultiPoint":
                intersectionPoints.extend(list(intersection.geoms))
            elif intersection.geom_type == "GeometryCollection":
                for geom in intersection.geoms:
                    if geom.geom_type == "Point":
                        intersectionPoints.append(geom)
                    elif geom.geom_type == "MultiPoint":
                        intersectionPoints.extend(list(geom.geoms))
            elif intersection.geom_type == "LineString":
                intersectionPoints.append(Point(intersection.coords[0]))
                intersectionPoints.append(Point(intersection.coords[-1]))
            elif intersection.geom_type == "MultiLineString":
                for geom in intersection.geoms:
                    if geom.geom_type == "LineString":
                        intersectionPoints.append(Point(geom.coords[0]))
                        intersectionPoints.append(Point(geom.coords[-1]))

        if len(intersectionPoints) >= 2:
            intersectionPoints.sort(key=lambda p: point.distance(p))
            
            p1Intersect = intersectionPoints[0]
            p2Intersect = intersectionPoints[-1]

            fullLine = LineString([p1Intersect, p2Intersect])
            distance = fullLine.length
            allDistances.append(distance)
            allLines.append(fullLine)
            allPoints.append(point)

    if allDistances:
        maxIdx = np.argmax(allDistances)
        maxDistance = allDistances[maxIdx]
        maxPoint = allPoints[maxIdx]
        maxLine = allLines[maxIdx]
    else:
        maxDistance = None
        maxPoint = None
        maxLine = None

    maxPerpendicularLength = maxDistance
    gdfShape['Basin width (Bw) (km)'] = maxPerpendicularLength/1000
    if tectonic is True:
        gdfTectonic['Basin shape index (Bs)'] = basinLength/maxPerpendicularLength
    return

def calculateWanderingRatio(gdfShape,gdfLinear,gdfStream,useLongestRiver):
    maxOrder = gdfLinear['Stream Order'].max()
    totalLength = gdfLinear.loc[gdfLinear['Stream Order'] == maxOrder, 'Stream length total (km)'].values[0]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfLinear['Wandering ratio (Rw)'] = None
            return

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])
        totalLength = (filterMaxOrder.geometry.iloc[0].length)/1000

    wanderingRatio = (totalLength/gdfShape['Basin length (Bl) (km)'])
    gdfLinear.loc[gdfLinear.index[-1], 'Wandering ratio (Rw)'] = wanderingRatio.iloc[0]
    return

def calculateStreamFrequency(gdfShape,gdfLinear):
    numStreams = gdfLinear['Stream number'].sum()
    streamFrequency = numStreams/gdfShape['Area (km2)']
    gdfLinear.loc[gdfLinear.index[-1], 'Stream frequency (Fs) (1/km2)'] = streamFrequency.iloc[0][0]
    if gpd.pd.isna(numStreams) or numStreams == 0:
        gdfLinear.loc[gdfLinear.index[-1], 'Stream frequency (Fs) (1/km2)'] = gpd.pd.NA
    return

def calculateDrainageDensity(gdfShape,gdfLinear):
    sumLengths = gdfLinear['Stream length total (km)'].sum()
    drainageDensity = sumLengths/gdfShape['Area (km2)']
    gdfLinear.loc[gdfLinear.index[-1], 'Drainage density (Dd) (km/km2)'] = drainageDensity.iloc[0][0]
    if gpd.pd.isna(sumLengths) or sumLengths == 0:
        gdfLinear.loc[gdfLinear.index[-1], 'Drainage density (Dd) (km/km2)'] = gpd.pd.NA
    return

def calculateDrainageTexture(gdfShape,gdfLinear):
    sumStreams = gdfLinear.loc[gdfLinear['Stream Order'] == 1, 'Stream number'].sum()
    perimeter = gdfShape['Perimeter (km)']
    drainageTexture = sumStreams/perimeter
    gdfLinear.loc[gdfLinear.index[-1], 'Drainage texture (Dt) (1/km)'] = drainageTexture.iloc[0][0]
    if gpd.pd.isna(sumStreams) or sumStreams == 0:
        gdfLinear.loc[gdfLinear.index[-1], 'Drainage texture (Dt) (1/km)'] = gpd.pd.NA
    return

def calculateLengthOverlandFlow(gdfLinear):
    lengthOverlandFlow = 1/(2*gdfLinear['Drainage density (Dd) (km/km2)'])
    gdfLinear['Length of overland flow (Lo) (km)'] = lengthOverlandFlow
    return

def calculateDrainageIntensity(gdfLinear):
    streamFrequency = gdfLinear['Stream frequency (Fs) (1/km2)']
    drainageDensity = gdfLinear['Drainage density (Dd) (km/km2)']
    drainageIntensity = streamFrequency/drainageDensity
    gdfLinear['Drainage intensity (Di) (1/km)'] = drainageIntensity
    return

def calculateInfiltrationNumber(gdfLinear):
    streamFrequency = gdfLinear['Stream frequency (Fs) (1/km2)']
    drainageDensity = gdfLinear['Drainage density (Dd) (km/km2)']
    drainageIntensity = streamFrequency*drainageDensity
    gdfLinear['Infiltration number (If) (km/km4)'] = drainageIntensity
    return

def calculateConstantChannel(gdfLinear):
    constantOfChannel = 1/gdfLinear['Drainage density (Dd) (km/km2)']
    gdfLinear['Constant of channel maintenance (Ccm) (km2/km)'] = constantOfChannel
    return

def calculateCirculatoryRatio(gdfShape):
    area = gdfShape['Area (km2)']
    perimeter = gdfShape['Perimeter (km)']
    gdfShape['Circulatory ratio (Rc)'] = 4*math.pi*area/(perimeter**2)
    return

def calculateElongationRatio(gdfShape):
    area = gdfShape['Area (km2)']
    length = gdfShape['Basin length (Bl) (km)']
    gdfShape['Elongation ratio (Re)'] = (2*(area/math.pi)**0.5)/length
    return

def calculateFormFactor(gdfShape):
    area = gdfShape['Area (km2)']
    length = gdfShape['Basin length (Bl) (km)']
    gdfShape['Form factor (Ff)'] = area/(length**2)
    return

def calculateLemniscateRatio(gdfShape):
    area = gdfShape['Area (km2)']
    length = gdfShape['Basin length (Bl) (km)']
    gdfShape['Lemniscate ratio (K)'] = (length**2)/(4*area)
    return

def calculateShapeIndex(gdfShape):
    area = gdfShape['Area (km2)']
    length = gdfShape['Basin length (Bl) (km)']
    gdfShape['Shape index (Sb)'] = (length**2)/area
    return

def calculateCompactnessCoefficient(gdfShape):
    area = gdfShape['Area (km2)']
    perimeter = gdfShape['Perimeter (km)']
    gdfShape['Compactness coefficient (Cc)'] = perimeter/(2*(math.pi*area)**0.5)
    return

def createGdfRelief():
    gdfRelief = gpd.GeoDataFrame(index=[0])
    return gdfRelief

def loadDEM(demLayer):
    DEMpath = demLayer.dataProvider().dataSourceUri().split('|')[0]
    ds = gdal.Open(DEMpath)
    band = ds.GetRasterBand(1)
    demArray = band.ReadAsArray()
    noData = band.GetNoDataValue() if band.GetNoDataValue() is not None else -9999
    gt = ds.GetGeoTransform()
    proj = ds.GetProjection()
    rows, cols = demArray.shape
    ds = None
    return demArray, noData, gt, proj, rows, cols

def calculateMinMaxMeanElevation(demArray,noData,gt,proj,rows,cols,basin,gdfRelief,feedback):
    basinGeom = basin.geometry()
    wkb = basinGeom.asWkb()
    ogrGeom = ogr.CreateGeometryFromWkb(wkb)

    rasterDrive = gdal.GetDriverByName('MEM')
    vectorDrive = ogr.GetDriverByName('Memory')
    vectorDriveSource    = vectorDrive.CreateDataSource('wrk')
    vectorLayer = vectorDriveSource.CreateLayer('lyr', None, ogr.wkbUnknown)
    featureDef   = vectorLayer.GetLayerDefn()
    ogrFeat  = ogr.Feature(featureDef)
    ogrFeat.SetGeometry(ogrGeom)
    vectorLayer.CreateFeature(ogrFeat)
    ogrFeat = None

    maskDS = rasterDrive.Create('', cols, rows, 1, gdal.GDT_Byte)
    maskDS.SetGeoTransform(gt)
    maskDS.SetProjection(proj)
    gdal.RasterizeLayer(maskDS, [1], vectorLayer, burn_values=[1])

    mask = maskDS.GetRasterBand(1).ReadAsArray()
    validMask = (mask == 1) & (demArray != noData)
    validDataInsideBasin = demArray[validMask].tolist()

    if not validDataInsideBasin:
        feedback.pushWarning('There is no valid raster data in the basin of id '+str(basin.id())+' and the calculation of some parameters for this basin may be compromised')
        gdfRelief['Minimum elevation (m)'] = None
        gdfRelief['Maximum elevation (m)'] = None
        gdfRelief['Mean elevation (m)'] = None
        return

    minElev = min(validDataInsideBasin)
    maxElev = max(validDataInsideBasin)
    meanElev = ((sum(validDataInsideBasin))/(len(validDataInsideBasin)))

    gdfRelief['Minimum elevation (m)'] = minElev
    gdfRelief['Maximum elevation (m)'] = maxElev
    gdfRelief['Mean elevation (m)'] = meanElev
    return

def calculateRelief(gdfRelief):
    minElevation = gdfRelief['Minimum elevation (m)']
    maxElevation = gdfRelief['Maximum elevation (m)']
    gdfRelief['Relief (Bh) (m)'] = maxElevation - minElevation
    return

def calculateReliefRatio(gdfRelief,gdfShape):
    relief = gdfRelief['Relief (Bh) (m)']
    reliefInKm = relief/1000
    length = gdfShape['Basin length (Bl) (km)']
    gdfRelief['Relief ratio (Rh)'] = reliefInKm/length
    return

def calculateRelativeRelief (gdfRelief,gdfShape):
    relief = gdfRelief['Relief (Bh) (m)']
    reliefInKm = relief/1000
    perimeter = gdfShape['Perimeter (km)']
    gdfRelief['Relative relief (Rhp)'] = reliefInKm/perimeter
    return

def calculateRuggednessNumber (gdfRelief,gdfLinear):
    relief = gdfRelief['Relief (Bh) (m)']
    reliefInKm = relief/1000
    drainageDensity = gdfLinear['Drainage density (Dd) (km/km2)'].iloc[-1]
    gdfRelief['Ruggedness number (Rn)'] = reliefInKm * drainageDensity
    return

def calculateDissectionIndex (gdfRelief):
    minElev = gdfRelief['Minimum elevation (m)']
    maxElev = gdfRelief['Maximum elevation (m)']
    gdfRelief['Dissection index (Di)'] = (maxElev - minElev)/maxElev
    return

def calculateGradientRatio(gdfStream,gdfLinear,dem,gdfRelief,useLongestRiver):
    if gdfStream.empty:
        gdfRelief['Gradient ratio (Gr)'] = None
        return

    maxOrder = gdfStream['order'].max()
    filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]

    firstPoint = filterMaxOrder.iloc[-1]['last']
    lastPoint = filterMaxOrder.iloc[0]['first']

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfLinear['Gradient ratio (Gr)'] = None
            return

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

        if mainRiver.geom_type == "LineString":

            firstPoint = tuple(mainRiver.coords[-1])
            lastPoint = tuple(mainRiver.coords[0])

        elif mainRiver.geom_type == "MultiLineString":

            firstLine = mainRiver.geoms[-1]
            lastLine = mainRiver.geoms[0]

            firstPoint = tuple(firstLine.coords[-1])
            lastPoint = tuple(lastLine.coords[0])
    
    firstPointQgs = QgsPointXY(firstPoint[0], firstPoint[1])
    lastPointQgs = QgsPointXY(lastPoint[0], lastPoint[1])

    identificatorFirst = dem.dataProvider().identify(firstPointQgs, QgsRaster.IdentifyFormat.IdentifyFormatValue)
    identificatorLast = dem.dataProvider().identify(lastPointQgs, QgsRaster.IdentifyFormat.IdentifyFormatValue)

    lowestPointKm = identificatorFirst.results()[1]/1000
    hightestPointKm = identificatorLast.results()[1]/1000

    if lowestPointKm is None or hightestPointKm is None:
        gdfRelief['Gradient ratio (Gr)'] = None
        return

    maxOrder = gdfLinear['Stream Order'].max()
    filteredMaxOrder = gdfLinear[gdfLinear['Stream Order'] == maxOrder]

    ls = filteredMaxOrder['Stream length total (km)'].values
    gdfRelief['Gradient ratio (Gr)'] = (hightestPointKm - lowestPointKm)/ls
    return

def calculateVoronoiSkeleton(gdf, n_points, min_length=0.0):
    geom = gdf.geometry.iloc[0]
    boundary = geom.boundary
    distances = np.linspace(0, boundary.length, n_points)
    points = [boundary.interpolate(d) for d in distances]
    coords = np.array([[p.x, p.y] for p in points])

    vor = Voronoi(coords)

    internalLines = []

    for ridge in vor.ridge_vertices:
        if -1 in ridge:
            continue

        p1 = vor.vertices[ridge[0]]
        p2 = vor.vertices[ridge[1]]

        line = LineString([p1, p2])

        if line.within(geom) and line.length > min_length:
            internalLines.append(line)

    if not internalLines:
        return None

    merged = unary_union(internalLines)
    merged = linemerge(merged)
    return merged

def longestPath(merged):
    if isinstance(merged, MultiLineString):
        lines = list(merged.geoms)
    else:
        lines = [merged]

    graph = {}

    def addEdge(p1, p2, weight):
        graph.setdefault(p1, []).append((p2, weight))
        graph.setdefault(p2, []).append((p1, weight))

    for line in lines:
        coords = list(line.coords)
        for i in range(len(coords) - 1):
            p1 = tuple(coords[i])
            p2 = tuple(coords[i + 1])

            length = LineString([p1, p2]).length
            addEdge(p1, p2, length)

    terminals = [node for node in graph if len(graph[node]) == 1]

    if len(terminals) < 2:
        return None

    def dijkstra(start):
        dist = {node: math.inf for node in graph}
        prev = {node: None for node in graph}

        dist[start] = 0
        visited = set()

        while len(visited) < len(graph):
            current = min(
                (n for n in graph if n not in visited),
                key=lambda n: dist[n],
                default=None
            )

            if current is None:
                break

            visited.add(current)

            for neighbor, weight in graph[current]:
                alt = dist[current] + weight
                if alt < dist[neighbor]:
                    dist[neighbor] = alt
                    prev[neighbor] = current

        return dist, prev

    maxDist = 0
    bestStart = None
    bestEnd = None
    bestPrev = None

    for start in terminals:
        dist, prev = dijkstra(start)

        for end in terminals:
            if dist[end] < math.inf and dist[end] > maxDist:
                maxDist = dist[end]
                bestStart = start
                bestEnd = end
                bestPrev = prev


    pathCoords = []
    current = bestEnd

    while current != bestStart:
        pathCoords.append(current)
        current = bestPrev[current]

    pathCoords.append(bestStart)
    pathCoords.reverse()


    centerline = LineString(pathCoords)
    return centerline

def longestDrainage(merged, startPoint):
    if isinstance(merged, MultiLineString):
        lines = list(merged.geoms)
    else:
        lines = [merged]

    graph = {}

    def addEdge(p1, p2, weight):
        graph.setdefault(p1, []).append((p2, weight))
        graph.setdefault(p2, []).append((p1, weight))


    for line in merged.geoms:

        coords = list(line.coords)

        for i in range(len(coords) - 1):

            p1 = tuple(coords[i])
            p2 = tuple(coords[i + 1])

            length = LineString([p1, p2]).length

            addEdge(
                p1,
                p2,
                length
            )


    startPointGeom = QgsGeometry.fromWkt(
        Point(startPoint).wkt
    )

    startPoint = tuple(
        wkt.loads(
            startPointGeom.asWkt()
        ).coords[0]
    )


    if startPoint not in graph:
        return None

    terminals = [
        node for node in graph
        if len(graph[node]) == 1
    ]


    def dijkstra(start):

        dist = {
            node: math.inf
            for node in graph
        }

        prev = {
            node: None
            for node in graph
        }

        dist[start] = 0

        visited = set()


        while len(visited) < len(graph):

            current = min(
                (
                    n for n in graph
                    if n not in visited
                ),
                key=lambda n: dist[n],
                default=None
            )


            if current is None:
                break


            visited.add(current)


            for neighbor, weight in graph[current]:

                alt = dist[current] + weight

                if alt < dist[neighbor]:

                    dist[neighbor] = alt
                    prev[neighbor] = current


        return dist, prev



    dist, prev = dijkstra(startPoint)

    reachableTerminals = [
        node for node in terminals
        if dist[node] != math.inf
    ]


    if len(reachableTerminals) == 0:
        return None


    farthestNode = max(
        reachableTerminals,
        key=lambda node: dist[node]
    )


    pathCoords = []

    current = farthestNode

    while current != startPoint:

        pathCoords.append(current)

        current = prev[current]

        if current is None:
            return None

    pathCoords.append(startPoint)

    if len(pathCoords) < 2:
        return None

    return LineString(pathCoords)

def createGdfTectonic():
    gdfTectonic = gpd.GeoDataFrame(index=[0])
    return gdfTectonic

def TransverseTopographicSymmetryFactor(midline, gdfStreamsInside, gdfShape, gdfTectonic, nPoints, basin, feedback, useLongestRiver):
    maxOrder = gdfStreamsInside['order'].max()
    filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStreamsInside.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfTectonic['Transverse topographic simmetry factor (TTSF)'] = None
            return

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

    lines = []

    for geom in gdfStreamsInside.geometry:

        if geom.geom_type == "LineString":
            lines.append(geom)

        elif geom.geom_type == "MultiLineString":
            lines.extend(list(geom.geoms))

    mainRiver = filterMaxOrder.geometry.iloc[0]

    boundary = gdfShape.geometry.unary_union.boundary

    fractions = np.linspace(
        0.1,
        0.9,
        nPoints
    )

    points = [
        midline.interpolate(
            fraction,
            normalized=True
        )
        for fraction in fractions
    ]


    distanceLines = []
    ttsValues = []
    noRiverPoints = 0


    for i, point in enumerate(points):

        eps = 0.001


        p1 = midline.interpolate(
            max(
                0,
                midline.project(point) - eps
            )
        )


        p2 = midline.interpolate(
            min(
                midline.length,
                midline.project(point) + eps
            )
        )


        dx = p2.x - p1.x
        dy = p2.y - p1.y


        nx = -dy
        ny = dx


        norm = np.sqrt(nx**2 + ny**2)


        if norm == 0:
            continue


        nx /= norm
        ny /= norm


        length = midline.length * 2


        linePositive = LineString([
            point,
            (
                point.x + nx * length,
                point.y + ny * length
            )
        ])


        lineNegative = LineString([
            point,
            (
                point.x - nx * length,
                point.y - ny * length
            )
        ])


        boundaryPositive = linePositive.intersection(
            boundary
        )

        boundaryNegative = lineNegative.intersection(
            boundary
        )


        def getNearestPoint(intersection, origin):

            if intersection.is_empty:
                return None

            if intersection.geom_type == "Point":

                return intersection

            elif intersection.geom_type == "MultiPoint":

                return min(
                    intersection.geoms,
                    key=lambda geom: origin.distance(geom)
                )

            elif intersection.geom_type == "GeometryCollection":

                points = [
                    geom
                    for geom in intersection.geoms
                    if geom.geom_type == "Point"
                ]

                if not points:
                    return None

                return min(
                    points,
                    key=lambda geom: origin.distance(geom)
                )

            return None

        boundaryPointPositive = getNearestPoint(
            boundaryPositive,
            point
        )

        boundaryPointNegative = getNearestPoint(
            boundaryNegative,
            point
        )

        validPositive = None
        validNegative = None


        if boundaryPointPositive is not None:

            validPositive = LineString([
                point,
                boundaryPointPositive
            ])


        if boundaryPointNegative is not None:

            validNegative = LineString([
                point,
                boundaryPointNegative
            ])

        riverPositive = None
        riverNegative = None


        if validPositive is not None:

            riverPositive = validPositive.intersection(
                mainRiver
            )


        if validNegative is not None:

            riverNegative = validNegative.intersection(
                mainRiver
            )

        riverCandidates = []


        if (
            riverPositive is not None
            and not riverPositive.is_empty
        ):

            riverPointPositive = getNearestPoint(
                riverPositive,
                point
            )

            if riverPointPositive is not None:

                riverCandidates.append({
                    "riverPoint": riverPointPositive,
                    "boundaryPoint": boundaryPointPositive
                })


        if (
            riverNegative is not None
            and not riverNegative.is_empty
        ):

            riverPointNegative = getNearestPoint(
                riverNegative,
                point
            )

            if riverPointNegative is not None:

                riverCandidates.append({
                    "riverPoint": riverPointNegative,
                    "boundaryPoint": boundaryPointNegative
                })

        if not riverCandidates:

            noRiverPoints += 1
            continue

        selected = min(
            riverCandidates,
            key=lambda candidate: point.distance(
                candidate["riverPoint"]
            )
        )


        riverPoint = selected["riverPoint"]

        boundaryPoint = selected["boundaryPoint"]

        midlineRiver = LineString([
            point,
            riverPoint
        ])


        midlineBoundary = LineString([
            point,
            boundaryPoint
        ])


        distanceLines.append({
            "id": i + 1,
            "type": "midlineRiver",
            "geometry": midlineRiver
        })


        distanceLines.append({
            "id": i + 1,
            "type": "midlineBoundary",
            "geometry": midlineBoundary
        })


        ttsValues.append({
            "id": i + 1,
            "distanceA": midlineRiver.length,
            "distanceB": midlineBoundary.length,
            "TTSF": midlineRiver.length /
                    (midlineBoundary.length)
        })


        distanceLines.append({
            "id": i + 1,
            "type": "riverPoint",
            "geometry": riverPoint
        })


        distanceLines.append({
            "id": i + 1,
            "type": "boundaryPoint",
            "geometry": boundaryPoint
        })


    if len(ttsValues) == 0:

        feedback.pushWarning(
            f"No points from the midline intersected the main river in basin ID {basin.id()}. "
            f"TTSF calculation could not be performed."
        )

        return None


    if noRiverPoints > 0:

        feedback.pushWarning(
            f"{noRiverPoints} point(s) did not intersect the main river in basin ID {basin.id()} "
            f"during the TTSF calculation."
        )


    gdf = gpd.GeoDataFrame(
        distanceLines,
        crs=gdfShape.crs
    )

    ttsMean = np.mean(
        [value["TTSF"] for value in ttsValues]
    )

    gdfTectonic.loc[
        gdfTectonic.index[-1],
        "Transverse topographic symmetry factor (TTSF)"
    ] = ttsMean


    return gdf
def assimetryIndex(gdfShape, gdfStreamsInside, gdfTectonic, useLongestRiver):
    maxOrder = gdfStreamsInside['order'].max()
    filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStreamsInside.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

    lines = []
    basin = gdfShape.geometry.unary_union

    for geom in gdfStreamsInside.geometry:

        if geom.geom_type == "LineString":
            lines.append(geom)

        elif geom.geom_type == "MultiLineString":
            lines.extend(list(geom.geoms))

    mainRiver = filterMaxOrder.geometry.iloc[0]

    if mainRiver.geom_type == "LineString":

        coords = list(mainRiver.coords)

    else:

        segments = list(mainRiver.geoms)

        coords = list(segments[0].coords)

        for seg in segments[1:]:

            segCoords = list(seg.coords)

            if coords[-1] == segCoords[0]:
                coords.extend(segCoords[1:])
            else:
                coords.extend(segCoords)

        mainRiver = LineString(coords)

    coords = list(mainRiver.coords)

    startPoint = Point(coords[-1])
    endPoint = Point(coords[0])

    dxStart = coords[0][0] - coords[1][0]
    dyStart = coords[0][1] - coords[1][1]

    dxEnd = coords[-1][0] - coords[-2][0]
    dyEnd = coords[-1][1] - coords[-2][1]


    extensionLength = max(
        basin.bounds[2] - basin.bounds[0],
        basin.bounds[3] - basin.bounds[1]
    ) * 10


    coords = list(mainRiver.coords)

    coords.insert(
        0,
        (
            startPoint.x + dxStart * extensionLength,
            startPoint.y + dyStart * extensionLength
        )
    )

    coords.append(
        (
            endPoint.x + dxEnd * extensionLength,
            endPoint.y + dyEnd * extensionLength
        )
    )

    extendedRiver = LineString(coords)
    extendedRiver = extendedRiver.intersection(basin)

    dividedBasin = split(
        basin,
        extendedRiver
    )

    parts = list(dividedBasin.geoms)

    leftParts = []
    rightParts = []


    for polygon in parts:

        point = polygon.representative_point()


        distance = mainRiver.project(point)
        riverPoint = mainRiver.interpolate(distance)


        delta = 1


        if distance + delta <= mainRiver.length:
            nextPoint = mainRiver.interpolate(distance + delta)
        else:
            nextPoint = mainRiver.interpolate(distance - delta)


        flowVectorX = nextPoint.x - riverPoint.x
        flowVectorY = nextPoint.y - riverPoint.y


        vectorX = point.x - riverPoint.x
        vectorY = point.y - riverPoint.y


        crossProduct = (
            flowVectorX * vectorY -
            flowVectorY * vectorX
        )


        if crossProduct > 0:
            leftParts.append(polygon)

        else:
            rightParts.append(polygon)



    leftArea = unary_union(leftParts)
    rightArea = unary_union(rightParts)


    parts = [
        leftArea,
        rightArea
    ]

    if len(parts) != 2:
        return None

    riverCenterDistance = mainRiver.length / 2

    delta = min(
        1,
        mainRiver.length * 0.01
    )

    nextPoint = mainRiver.interpolate(
        min(mainRiver.length, riverCenterDistance + delta)
    )

    rightAreaNumber = None


    for polygon in parts:

        point = polygon.representative_point()

        distance = mainRiver.project(point)

        riverPoint = mainRiver.interpolate(
            distance
        )

        delta = 1

        if distance + delta <= mainRiver.length:

            nextPoint = mainRiver.interpolate(
                distance + delta
            )

        else:

            nextPoint = mainRiver.interpolate(
                distance - delta
            )

        flowVectorX = nextPoint.x - riverPoint.x
        flowVectorY = nextPoint.y - riverPoint.y

        vectorX = point.x - riverPoint.x
        vectorY = point.y - riverPoint.y

        crossProduct = (
            flowVectorX * vectorY -
            flowVectorY * vectorX
        )

        if crossProduct > 0:

            rightAreaNumber = polygon.area
            break


    if rightArea is None:
        return None

    asymmetryIndex = rightAreaNumber / basin.area

    gdfTectonic.loc[
        gdfTectonic.index[-1],
        "Assimetry factor (AF)"
    ] = asymmetryIndex

    return asymmetryIndex
def calculateSLindexMainChannel(gdfStream,dem,gdfTectonic,useLongestRiver,nSectionsSL):
    maxOrder = gdfStream['order'].max()
    filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStream.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfTectonic['Stream-length index mean (SLm)'] = None
            return

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStream[gdfStream['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

    nSections = nSectionsSL

    riverLength = filterMaxOrder.geometry.iloc[0].length
    sectionLength = riverLength / nSections

    sections = []
    river = filterMaxOrder.geometry.iloc[0]

    if river.geom_type == "MultiLineString":
        river = linemerge(river)

    if river.geom_type != "LineString":
        gdfTectonic['Stream-length index mean (SLm)'] = None
        return

    riverLength = river.length
    sectionLength = riverLength / nSections

    sections = []

    for i in range(nSections):

        startDistance = i * sectionLength
        endDistance = (i + 1) * sectionLength

        section = substring(
            river,
            startDistance,
            endDistance
        )

        sections.append(section)

    filterMaxOrder = gpd.GeoDataFrame(
        {
            'section': range(1, nSections + 1),
            'geometry': sections
        },
        crs=gdfStream.crs
    )
    filterMaxOrder['center'] = filterMaxOrder.geometry.interpolate(0.5, normalized=True)

    filterMaxOrder['length'] = filterMaxOrder.geometry.length

    filterMaxOrder['distance'] = (
        filterMaxOrder['length'].cumsum()
        - filterMaxOrder['length'] / 2
    )

    upstreamElevations = []
    downstreamElevations = []
    elevationDifferences = []

    for line in filterMaxOrder.geometry:

        upstreamPoint = line.interpolate(0, normalized=True)

        upstreamPointQgs = QgsPointXY(
            upstreamPoint.x,
            upstreamPoint.y
        )

        identificatorUpstream = dem.dataProvider().identify(
            upstreamPointQgs,
            QgsRaster.IdentifyFormat.IdentifyFormatValue
        )

        if identificatorUpstream.isValid():
            upstreamElevation = identificatorUpstream.results().get(1)
        else:
            upstreamElevation = None


        downstreamPoint = line.interpolate(1, normalized=True)

        downstreamPointQgs = QgsPointXY(
            downstreamPoint.x,
            downstreamPoint.y
        )

        identificatorDownstream = dem.dataProvider().identify(
            downstreamPointQgs,
            QgsRaster.IdentifyFormat.IdentifyFormatValue
        )

        if identificatorDownstream.isValid():
            downstreamElevation = identificatorDownstream.results().get(1)
        else:
            downstreamElevation = None

        if (
            upstreamElevation is not None
            and downstreamElevation is not None
        ):
            elevationDifference = (
                upstreamElevation - downstreamElevation
            )
        else:
            elevationDifference = None


        upstreamElevations.append(upstreamElevation)
        downstreamElevations.append(downstreamElevation)
        elevationDifferences.append(elevationDifference)


    filterMaxOrder['upstream_elevation'] = upstreamElevations
    filterMaxOrder['downstream_elevation'] = downstreamElevations
    filterMaxOrder['elevation_difference'] = elevationDifferences

    filterMaxOrder['SL'] = (
        (filterMaxOrder['elevation_difference']
        / filterMaxOrder['length'])
        * filterMaxOrder['distance']
    )
    filterMaxOrder['SLt'] = filterMaxOrder['elevation_difference'] / np.log(filterMaxOrder['distance'])

    gdfTectonic['Stream-Length index mean (SLm)'] = None
    gdfTectonic['Stream-Length index mean (SLm)'] = filterMaxOrder['SL'].mean()

    gdfTectonic['Stream-Length index total mean (SLtm)'] = None
    gdfTectonic['Stream-Length index total mean (SLtm)'] = filterMaxOrder['SLt'].mean()

    gdfTectonic['Stream-Length index (SLm/SLtm)'] = gdfTectonic['Stream-Length index mean (SLm)']/gdfTectonic['Stream-Length index total mean (SLtm)']
    return

def valleyFloorWidthHeight(gdfStreamsInside, gdfShape, nPoints, dem, gdfTectonic, limitForValleyFloor, minForValleyHeight, feedback, useLongestRiver, limitDescendValley):

    maxOrder = gdfStreamsInside["order"].max()
    filterMaxOrder = gdfStreamsInside[gdfStreamsInside["order"] == maxOrder]

    mainRiver = filterMaxOrder.geometry.iloc[0]

    if useLongestRiver is True:

        lines = []

        for geom in gdfStreamsInside.geometry:

            if geom is None or geom.is_empty:
                continue

            if geom.geom_type == "LineString":
                lines.append(geom)

            elif geom.geom_type == "MultiLineString":
                lines.extend(list(geom.geoms))

        if not lines:
            gdfTectonic['Valley floor width-height ratio (Vf)'] = None
            return

        merged = MultiLineString(lines)
        filterMaxOrder = gdfStreamsInside[gdfStreamsInside['order'] == maxOrder]
        mainRiver = longestDrainage(
            merged,
            tuple(filterMaxOrder.iloc[-1]['last'])
        )
        
        filterMaxOrder = gpd.GeoDataFrame(geometry=[mainRiver])

    boundary = gdfShape.geometry.unary_union

    fractions = np.linspace(
        0.1,
        0.9,
        nPoints
    )

    points = [
        mainRiver.interpolate(
            fraction,
            normalized=True
        )
        for fraction in fractions
    ]

    transverseLines = []

    for i, point in enumerate(points):

        eps = 0.001

        p1 = mainRiver.interpolate(
            max(
                0,
                mainRiver.project(point) - eps
            )
        )

        p2 = mainRiver.interpolate(
            min(
                mainRiver.length,
                mainRiver.project(point) + eps
            )
        )

        dx = p2.x - p1.x
        dy = p2.y - p1.y

        nx = -dy
        ny = dx

        norm = np.sqrt(nx ** 2 + ny ** 2)

        if norm == 0:
            continue

        nx /= norm
        ny /= norm

        length = max(
            boundary.bounds[2] - boundary.bounds[0],
            boundary.bounds[3] - boundary.bounds[1]
        ) * 2

        line = LineString([
            (
                point.x - nx * length,
                point.y - ny * length
            ),
            (
                point.x + nx * length,
                point.y + ny * length
            )
        ])

        clipped = line.intersection(boundary)

        if clipped.is_empty:
            continue

        if clipped.geom_type == "LineString":

            transverseLines.append({
                "id": i + 1,
                "geometry": clipped
            })

        elif clipped.geom_type == "MultiLineString":

            largest = max(
                clipped.geoms,
                key=lambda geom: geom.length
            )

            transverseLines.append({
                "id": i + 1,
                "geometry": largest
            })

    gdf = gpd.GeoDataFrame(
        transverseLines,
        crs=gdfShape.crs
    )

    provider = dem.dataProvider()

    gdf["profile"] = None
    gdf["river_point"] = None
    gdf["river_elevation"] = None
    gdf["left_point"] = None
    gdf["left_elevation"] = None
    gdf["right_point"] = None
    gdf["right_elevation"] = None
    gdf["left_1m_point"] = None
    gdf["left_1m_elevation"] = None
    gdf["right_1m_point"] = None
    gdf["right_1m_elevation"] = None
    gdf["width_1m"] = None
    gdf["lowest_point"] = None
    gdf["lowest_elevation"] = None
    gdf["vf_ratio"] = None
    discardedSections = 0
    for idx, row in gdf.iterrows():

        line = row.geometry

        profile = []

        distance = 0

        while distance <= line.length:

            samplePoint = line.interpolate(distance)

            pointQgs = QgsPointXY(
                samplePoint.x,
                samplePoint.y
            )

            identify = provider.identify(
                pointQgs,
                QgsRaster.IdentifyFormat.IdentifyFormatValue
            )

            if identify.isValid():

                value = identify.results().get(1)

                if value is not None:

                    profile.append({
                        "point": samplePoint,
                        "distance": distance,
                        "elevation": value
                    })

            distance += 1

        if len(profile) < 3:
            discardedSections += 1
            continue

        intersection = line.intersection(mainRiver)

        if intersection.is_empty:
            discardedSections += 1
            continue

        if intersection.geom_type == "MultiPoint":
            intersection = list(intersection.geoms)[0]

        pointQgs = QgsPointXY(
            intersection.x,
            intersection.y
        )

        identify = provider.identify(
            pointQgs,
            QgsRaster.IdentifyFormat.IdentifyFormatValue
        )

        if identify.isValid():
            riverElevation = identify.results().get(1)
        else:
            riverElevation = None

        gdf.at[idx, "river_point"] = intersection
        gdf.at[idx, "river_elevation"] = riverElevation

        profile.append({
            "point": intersection,
            "distance": line.project(intersection),
            "elevation": riverElevation
        })

        profile.sort(key=lambda p: p["distance"])

        riverIndex = next(
            i for i, p in enumerate(profile)
            if p["point"].equals(intersection)
        )

        leftIndex = riverIndex

        while leftIndex > 0:

            diff = profile[leftIndex - 1]["elevation"] - profile[leftIndex]["elevation"]

            if diff >= -(limitDescendValley):
                leftIndex -= 1
            else:
                break

        rightIndex = riverIndex

        while rightIndex < len(profile) - 1:

            diff = profile[rightIndex + 1]["elevation"] - profile[rightIndex]["elevation"]

            if diff >= -(limitDescendValley):
                rightIndex += 1
            else:
                break


        leftOneMeter = riverIndex

        for i in range(riverIndex - 1, leftIndex - 1, -1):
            diff = profile[i]["elevation"] - riverElevation

            if diff < limitForValleyFloor:
                leftOneMeter = i
            else:
                break

        rightOneMeter = riverIndex

        for i in range(riverIndex + 1, rightIndex + 1):
            diff = profile[i]["elevation"] - riverElevation

            if diff < limitForValleyFloor:
                rightOneMeter = i
            else:
                break

        if leftOneMeter is not None:
            gdf.at[idx, "left_1m_point"] = profile[leftOneMeter]["point"]
            gdf.at[idx, "left_1m_elevation"] = profile[leftOneMeter]["elevation"]

        if rightOneMeter is not None:
            gdf.at[idx, "right_1m_point"] = profile[rightOneMeter]["point"]
            gdf.at[idx, "right_1m_elevation"] = profile[rightOneMeter]["elevation"]

        if leftOneMeter is not None and rightOneMeter is not None:
            gdf.at[idx, "width_1m"] = (
                profile[leftOneMeter]["point"].distance(
                    profile[rightOneMeter]["point"]
                )
            )

        gdf.at[idx, "left_point"] = profile[leftIndex]["point"]
        gdf.at[idx, "left_elevation"] = profile[leftIndex]["elevation"]

        gdf.at[idx, "right_point"] = profile[rightIndex]["point"]
        gdf.at[idx, "right_elevation"] = profile[rightIndex]["elevation"]

        gdf.at[idx, "profile"] = profile

        start = min(leftIndex, rightIndex)
        end = max(leftIndex, rightIndex)

        lowestIndex = min(
            range(start, end + 1),
            key=lambda i: profile[i]["elevation"]
        )

        gdf.at[idx, "lowest_point"] = profile[lowestIndex]["point"]
        gdf.at[idx, "lowest_elevation"] = profile[lowestIndex]["elevation"]

        leftDiff = profile[leftIndex]["elevation"] - profile[lowestIndex]["elevation"]
        rightDiff = profile[rightIndex]["elevation"] - profile[lowestIndex]["elevation"]

        minRelief = minForValleyHeight
        if leftDiff == 0 or rightDiff == 0:
            discardedSections += 1
            continue

        if leftDiff < minRelief or rightDiff < minRelief:
            discardedSections += 1
            continue

        denominator = leftDiff + rightDiff

        gdf.at[idx, "vf_ratio"] = (
            2 * gdf.at[idx, "width_1m"] / denominator
        )
    
    gdfTectonic.loc[gdfTectonic.index[-1], "Valley floor width-height ratio (Vf)"] = gdf["vf_ratio"].mean()
    if discardedSections > 0:
        feedback.pushWarning(
            f"{discardedSections} transverse section(s) were discarded "
            f"during the Valley floor width-height ratio (Vf) calculation."
        )
    if discardedSections == len(gdf):
        feedback.pushWarning(
            f"No transverse sections were successfully processed "
            f"during the Valley floor width-height ratio (Vf) calculation."
        )
    return gdf
def createGdfFront(fronts):
    if fronts is None:
        return gpd.GeoDataFrame(geometry=[])
    frontsQgs = []
    for geom in fronts:
        if geom and not geom.is_empty:
            qgs_geom = QgsGeometry.fromWkt(geom.wkt)
            frontsQgs.append(qgs_geom)
    geometries2d = []

    for feat in frontsQgs:
        if feat.constGet() is None:
            continue
        if feat.constGet().is3D():
            feat.get().dropZValue()
        if feat.constGet().isMeasure():
            feat.get().dropMValue()

        if not feat.isMultipart():
            geomType = feat.wkbType()
            if QgsWkbTypes.geometryType(geomType) != QgsWkbTypes.GeometryType.PointGeometry:
                geometries2d.append(feat)

        else:
            multiGeom = feat.asGeometryCollection()
            for part in multiGeom:
                geomType = part.wkbType()
                if QgsWkbTypes.geometryType(geomType) != QgsWkbTypes.GeometryType.PointGeometry:
                    geometries2d.append(part)

    gdfFronts = gpd.GeoDataFrame(
        geometry=geometries2d
    )
    return gdfFronts
def selectFrontsInsideLayer(mountainFronts, drainageBasinLayer, feedback):
    if mountainFronts is None:
        return mountainFronts
    frontsWithinLayer = []

    frontsShapes = [
        wkt.loads(fronts.geometry().asWkt())
        for fronts in mountainFronts.getFeatures()
    ]
    streamsUnion = unary_union(frontsShapes)

    for basin in drainageBasinLayer.getFeatures():

        basinShape = wkt.loads(basin.geometry().asWkt())

        intersection = streamsUnion.intersection(basinShape)

        if intersection.is_empty:
            feedback.pushWarning(
                'There are no mountain fronts within the basin of id '
                + str(basin.id())
                + ' and the calculation of some parameters for this basin may be compromised'
            )
            continue

        if intersection.geom_type in ("LineString", "MultiLineString"):
            geoms = [intersection]
        else:
            geoms = [
                g for g in intersection.geoms
                if g.geom_type in ("LineString", "MultiLineString")
            ]
        for geom in geoms:
            frontsWithinLayer.append(geom)

    return frontsWithinLayer

def createMountainFrontsGdf(mountainFronts):
    geometries2d = []

    for feat in mountainFronts:
        if feat.constGet() is None:
            continue
        if feat.constGet().is3D():
            feat.get().dropZValue()
        if feat.constGet().isMeasure():
            feat.get().dropMValue()

        if not feat.isMultipart():
            geomType = feat.wkbType()
            if QgsWkbTypes.geometryType(geomType) != QgsWkbTypes.GeometryType.PointGeometry:
                geometries2d.append(feat)

        else:
            multiGeom = feat.asGeometryCollection()
            for part in multiGeom:
                geomType = part.wkbType()
                if QgsWkbTypes.geometryType(geomType) != QgsWkbTypes.GeometryType.PointGeometry:
                    geometries2d.append(part)

    gdfFronts = gpd.GeoDataFrame(
        geometry=geometries2d
    )
    return gdfFronts

def selectFrontsInsideBasin(mountainFronts, drainageBasinGdf):
    linesInBasins = gpd.overlay(mountainFronts, drainageBasinGdf, how="intersection", keep_geom_type=False)

    if linesInBasins.empty:
        return linesInBasins

    coords = linesInBasins.geometry.apply(
        lambda geom: (
            [geom.coords[0], geom.coords[-1]] if geom.geom_type == "LineString"
            else [list(geom.geoms[0].coords)[0], list(geom.geoms[-1].coords)[-1]] if geom.geom_type == "MultiLineString"
            else [None, None]
        )
    )

    linesInBasins["first"] = coords.str[0]
    linesInBasins["last"]  = coords.str[1]
    
    return linesInBasins

def mountainFrontSinuosity(mountainFronts, gdfTectonic):
    if mountainFronts.empty:
        gdfTectonic['Mountain front sinuosity index (Smf)'] = None
        return

    totalLength = mountainFronts.length.mean()
    straightLineDistances = []
    for _, row in mountainFronts.iterrows():
        firstPoint = row['first']
        lastPoint = row['last']
        
        straightLine = QgsGeometry.fromPolylineXY([
            QgsPointXY(firstPoint[0], firstPoint[1]),
            QgsPointXY(lastPoint[0], lastPoint[1])
        ])
        
        straightLineDistance = straightLine.length()
        straightLineDistances.append(straightLineDistance)

    averageStraightLineDistance = sum(straightLineDistances) / len(straightLineDistances)

    if averageStraightLineDistance == 0:
        gdfTectonic['Mountain front sinuosity (Smf)'] = None
        return
    smf = totalLength / averageStraightLineDistance

    gdfTectonic['Mountain front sinuosity (Smf)'] = smf

    return smf

def intToRoman(num):
    val = [1000, 900, 500, 400, 100, 90,  50,  40, 10, 9, 5, 4, 1]
    syms = ['M', 'CM', 'D', 'CD', 'C', 'XC', 'L', 'XL', 'X', 'IX', 'V', 'IV', 'I']
    roman = ''
    for i in range(len(val)):
        count = num // val[i]
        roman += syms[i] * count
        num -= val[i] * count
    return roman

def createGdfConcatenated(gdfLinear,gdfShape,gdfRelief,basin,gdfTectonic):
    gdfLinearGeneral = gdfLinear[gdfLinear['Stream Order'].isna()].drop(columns='Stream Order').reset_index(drop=True)

    gdfLinearOrders = gdfLinear[gdfLinear['Stream Order'].notna()].copy()
    gdfLinearOrders['Stream Order'] = gdfLinearOrders['Stream Order'].astype(int)

    columnsToPivote = [
        col for col in gdfLinearOrders.columns
        if col not in ['Stream Order', '__row__'] and gdfLinearOrders[col].notna().any()
    ]

    gdfLinearOrders = gdfLinearOrders[['Stream Order'] + columnsToPivote]
    gdfLinearOrders['__row__'] = 0
    gdfLinearPivoted = gdfLinearOrders.pivot(index='__row__', columns='Stream Order')

    gdfLinearPivoted.columns = [
        f'{col[0]} {intToRoman(col[1])}' for col in gdfLinearPivoted.columns
    ]
    gdfLinearPivoted = gdfLinearPivoted.reset_index(drop=True)

    pivotedColumnsBase = set(col.split(' ')[0] for col in gdfLinearPivoted.columns)
    columnsWithoutPivote = [col for col in gdfLinearGeneral.columns if col not in pivotedColumnsBase]

    gdfLinearGeneralFiltered = gdfLinearGeneral[columnsWithoutPivote].dropna(axis=1, how='all')
    finalGdfLinear = gpd.pd.concat([gdfLinearPivoted, gdfLinearGeneralFiltered], axis=1)
    finalGdfLinear.index = ['Basin id ' + str(basin.id())]

    gdfShape.drop(columns='geometry', inplace=True)
    for col in gdfShape.columns:
        gdfShape[col] = [x.iloc[0] if hasattr(x, "iloc") else x for x in gdfShape[col]]
    finalGdfShapeFloat = gdfShape.astype(float)
    finalGdfShapeFloat.index = ['Basin id ' + str(basin.id())]

    for col in gdfRelief.columns:
        gdfRelief[col] = [x.iloc[0] if hasattr(x, "iloc") else x for x in gdfRelief[col]]
    finalGdfReliefFloat = gdfRelief.astype(float)
    finalGdfReliefFloat.index = ['Basin id ' + str(basin.id())]

    for col in gdfTectonic.columns:

        gdfTectonic[col] = [x.iloc[0] if hasattr(x, "iloc") else x for x in gdfTectonic[col]]
    finalGdfTectonicFloat = gdfTectonic.astype(float)
    finalGdfTectonicFloat.index = ['Basin id ' + str(basin.id())]
    gdfFinalAll = gpd.pd.concat([finalGdfLinear, finalGdfShapeFloat, finalGdfReliefFloat, finalGdfTectonicFloat], ignore_index=False, axis=1)

    return gdfFinalAll

def formatGdfLinear(gdfLinear,basin):
    gdfLinearGeneral = gdfLinear[gdfLinear['Stream Order'].isna()].drop(columns='Stream Order').reset_index(drop=True)

    gdfLinearOrders = gdfLinear[gdfLinear['Stream Order'].notna()].copy()
    gdfLinearOrders['Stream Order'] = gdfLinearOrders['Stream Order'].astype(int)

    columnsToPivote = [
        col for col in gdfLinearOrders.columns
        if col not in ['Stream Order', '__row__'] and gdfLinearOrders[col].notna().any()
    ]

    gdfLinearOrders = gdfLinearOrders[['Stream Order'] + columnsToPivote]
    gdfLinearOrders['__row__'] = 0
    gdfLinearPivoted = gdfLinearOrders.pivot(index='__row__', columns='Stream Order')

    gdfLinearPivoted.columns = [
        f'{col[0]} {intToRoman(col[1])}' for col in gdfLinearPivoted.columns
    ]
    gdfLinearPivoted = gdfLinearPivoted.reset_index(drop=True)

    pivotedColumnsBase = set(col.split(' ')[0] for col in gdfLinearPivoted.columns)
    columnsWithoutPivote = [col for col in gdfLinearGeneral.columns if col not in pivotedColumnsBase]

    gdfLinearGeneralFiltered = gdfLinearGeneral[columnsWithoutPivote].dropna(axis=1, how='all')

    finalGdfLinear = gpd.pd.concat([gdfLinearPivoted, gdfLinearGeneralFiltered], axis=1)

    finalGdfLinear.index = ['Basin id ' + str(basin.id())]
    return finalGdfLinear

def formatGdfShape(gdfShape,basin):
    gdfShape.drop(columns='geometry', inplace=True)
    for col in gdfShape.columns:
        gdfShape[col] = [x.iloc[0] if hasattr(x, "iloc") else x for x in gdfShape[col]]
    gdfShapeFloat = gdfShape.astype(float)
    gdfShapeFloat.index = ['Basin id ' + str(basin.id())]
    return gdfShapeFloat

def formatGdfRelief(gdfRelief,basin):
    for col in gdfRelief.columns:
        gdfRelief[col] = [x.iloc[0] if hasattr(x, "iloc") else x for x in gdfRelief[col]]
    gdfReliefFloat = gdfRelief.astype(float)
    gdfReliefFloat.index = ['Basin id ' + str(basin.id())]
    return gdfReliefFloat

def formatGdfTectonic(gdfTectonic,basin):
    for col in gdfTectonic.columns:
        gdfTectonic[col] = [x.iloc[0] if hasattr(x, "iloc") else x for x in gdfTectonic[col]]
    finalGdfTectonicFloat = gdfTectonic.astype(float)
    finalGdfTectonicFloat.index = ['Basin id ' + str(basin.id())]
    return finalGdfTectonicFloat

def calculateMorphometrics(demArray,noData,gt,proj,rows,cols,drainageBasinLayer,streamLayer,demLayer,path,feedback,decimalPlaces,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nPointsMidline,nSectionsSL,mountainFronts,nPointsValley,limitDescendValley,nPointsBs):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfConcatenateds = []
    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    mountainFrontsInsideLayer = selectFrontsInsideLayer(mountainFronts, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    gdfFronts = createGdfFront(mountainFrontsInsideLayer)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside)
        gdfLinear = createGdfLinear(gdfStreamsInside)
        calculateStreamNumber(gdfStreamsInside,gdfLinear)
        calculateTotalStreamLength(gdfStreamsInside,gdfLinear)
        calculateMeanStreamLength(gdfStreamsInside,gdfLinear)
        calculateStreamLengthRatio(gdfLinear)
        calculateStreamLengthRatioMean(gdfLinear)
        calculateBifurcationRatio(gdfLinear)
        calculateBifurcationRatioMean(gdfLinear)
        calculateRhoCoefficient(gdfLinear)
        calculateSinuosityIndex(gdfStreamsInside,gdfLinear,useLongestRiver)
        if feedback.isCanceled():
            return
        calculateAreaPerimeter(gdfShape)
        calculateFitnessRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver)
        gdfTectonic = createGdfTectonic()
        calculateBasinLength(gdfStreamsInside,gdfShape,basin,feedback,useLongestRiver,gdfTectonic,tectonic=True,nPoints=nPointsBs)
        calculateWanderingRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver)
        calculateDrainageDensity(gdfShape,gdfLinear)
        calculateStreamFrequency(gdfShape,gdfLinear)
        calculateDrainageTexture(gdfShape,gdfLinear)
        calculateLengthOverlandFlow(gdfLinear)
        calculateConstantChannel(gdfLinear)
        calculateDrainageIntensity(gdfLinear)
        calculateInfiltrationNumber(gdfLinear)
        calculateCirculatoryRatio(gdfShape)
        calculateElongationRatio(gdfShape)
        calculateFormFactor(gdfShape)
        calculateLemniscateRatio(gdfShape)
        calculateShapeIndex(gdfShape)
        calculateCompactnessCoefficient(gdfShape)
        if feedback.isCanceled():
            return
        gdfRelief = createGdfRelief()
        calculateMinMaxMeanElevation(demArray,noData,gt,proj,rows,cols,basin,gdfRelief,feedback)
        calculateRelief(gdfRelief)
        calculateReliefRatio(gdfRelief,gdfShape)
        calculateRelativeRelief(gdfRelief,gdfShape)
        calculateRuggednessNumber(gdfRelief,gdfLinear)
        calculateDissectionIndex(gdfRelief)
        calculateGradientRatio(gdfStreamsInside,gdfLinear,demLayer,gdfRelief,useLongestRiver)
        if feedback.isCanceled():
            return
        skelet = calculateVoronoiSkeleton(gdfShape, nPointsMidline, min_length=0.0)
        midline = longestPath(skelet)
        TransverseTopographicSymmetryFactor(midline, gdfStreamsInside, gdfShape, gdfTectonic, nPoints, basin, feedback, useLongestRiver)
        assimetryIndex(gdfShape, gdfStreamsInside, gdfTectonic, useLongestRiver)
        calculateSLindexMainChannel(gdfStreamsInside,demLayer,gdfTectonic,useLongestRiver, nSectionsSL)
        if feedback.isCanceled():
            return
        valleyFloorWidthHeight(gdfStreamsInside, gdfShape, nPointsValley, demLayer, gdfTectonic, limitForValleyFloor, minForValleyHeight, feedback, useLongestRiver, limitDescendValley)
        mountainFrontsInsidebasin = selectStreamsInsideBasin(gdfFronts, gdfShape, basin, feedback, streams=False)
        mountainFrontSinuosity(mountainFrontsInsidebasin, gdfTectonic)
        gdfConcatenated = createGdfConcatenated(gdfLinear,gdfShape,gdfRelief,basin,gdfTectonic)
        gdfConcatenateds.append(gdfConcatenated)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return

    gdfMostColumns = max(gdfConcatenateds, key=lambda df: len(df.columns))
    gdfFinal = gpd.pd.concat(gdfConcatenateds, ignore_index=False, axis=0, sort=False)
    gdfFinal = gdfFinal.reindex(columns=gdfMostColumns.columns)
    gdfFinal.to_csv(path, index=True, header=True, float_format='%.' + str(decimalPlaces)+ 'f')

    return

def calculateLinearParameters(drainageBasinLayer,streamLayer,path,feedback,decimalPlaces,useLongestRiver):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfsLinear = []
    
    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside)
        gdfLinear = createGdfLinear(gdfStreamsInside)
        if feedback.isCanceled():
            return
        calculateStreamNumber(gdfStreamsInside,gdfLinear)
        calculateTotalStreamLength(gdfStreamsInside,gdfLinear)
        calculateMeanStreamLength(gdfStreamsInside,gdfLinear)
        calculateStreamLengthRatio(gdfLinear)
        calculateStreamLengthRatioMean(gdfLinear)
        calculateBifurcationRatio(gdfLinear)
        calculateBifurcationRatioMean(gdfLinear)
        calculateRhoCoefficient(gdfLinear)
        calculateSinuosityIndex(gdfStreamsInside,gdfLinear,useLongestRiver)
        if feedback.isCanceled():
            return
        gdfShape = createGdfShape(basin)
        calculateAreaPerimeter(gdfShape)
        calculateFitnessRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver)
        calculateBasinLength(gdfStreamsInside,gdfShape,basin,feedback,useLongestRiver,gdfTectonic=None,tectonic=False,nPoints=None)
        calculateWanderingRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver)
        calculateDrainageDensity(gdfShape,gdfLinear)
        calculateStreamFrequency(gdfShape,gdfLinear)
        calculateDrainageTexture(gdfShape,gdfLinear)
        calculateLengthOverlandFlow(gdfLinear)
        calculateConstantChannel(gdfLinear)
        calculateDrainageIntensity(gdfLinear)
        calculateInfiltrationNumber(gdfLinear)
        if feedback.isCanceled():
            return
        gdfFormated = formatGdfLinear(gdfLinear,basin)
        gdfsLinear.append(gdfFormated)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return
    gdfMostColumns = max(gdfsLinear, key=lambda df: len(df.columns))
    gdfFinal = gpd.pd.concat(gdfsLinear, ignore_index=False, axis=0, sort=False)
    gdfFinal = gdfFinal.reindex(columns=gdfMostColumns.columns)
    gdfFinal.to_csv(path, index=True, header=True, float_format='%.' + str(decimalPlaces)+ 'f')

    return

def calculateShapeParameters(drainageBasinLayer,streamLayer,path, feedback,decimalPlaces,useLongestRiver,nPointsBs):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfsShape = []
    
    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside)
        calculateAreaPerimeter(gdfShape)
        calculateBasinLength(gdfStreamsInside,gdfShape,basin,feedback,useLongestRiver,gdfTectonic=None,tectonic=False,nPoints=nPointsBs)
        calculateCirculatoryRatio(gdfShape)
        calculateElongationRatio(gdfShape)
        calculateFormFactor(gdfShape)
        calculateLemniscateRatio(gdfShape)
        calculateShapeIndex(gdfShape)
        calculateCompactnessCoefficient(gdfShape)
        if feedback.isCanceled():
            return
        gdfFormated = formatGdfShape(gdfShape,basin)
        gdfsShape.append(gdfFormated)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return
    gdfMostColumns = max(gdfsShape, key=lambda df: len(df.columns))
    gdfFinal = gpd.pd.concat(gdfsShape, ignore_index=False, axis=0, sort=False)
    gdfFinal = gdfFinal.reindex(columns=gdfMostColumns.columns)
    gdfFinal.to_csv(path, index=True, header=True, float_format='%.' + str(decimalPlaces)+ 'f')

    return

def calculateReliefParameters(demArray,noData,gt,proj,rows,cols,drainageBasinLayer,streamLayer,demLayer,path,feedback,decimalPlaces,useLongestRiver):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfsRelief = []

    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside)
        gdfLinear = createGdfLinear(gdfStreamsInside)
        calculateStreamNumber(gdfStreamsInside,gdfLinear)
        calculateTotalStreamLength(gdfStreamsInside,gdfLinear)
        if feedback.isCanceled():
            return
        calculateAreaPerimeter(gdfShape)
        calculateBasinLength(gdfStreamsInside,gdfShape,basin,feedback,useLongestRiver,gdfTectonic=None,tectonic=False,nPoints=None)
        calculateDrainageDensity(gdfShape,gdfLinear)
        if feedback.isCanceled():
            return
        gdfRelief = createGdfRelief()
        calculateMinMaxMeanElevation(demArray,noData,gt,proj,rows,cols,basin,gdfRelief,feedback)
        calculateRelief(gdfRelief)
        calculateReliefRatio(gdfRelief,gdfShape)
        calculateRelativeRelief(gdfRelief,gdfShape)
        calculateRuggednessNumber(gdfRelief,gdfLinear)
        calculateDissectionIndex(gdfRelief)
        calculateGradientRatio(gdfStreamsInside,gdfLinear,demLayer,gdfRelief,useLongestRiver)
        if feedback.isCanceled():
            return
        gdfFormated = formatGdfRelief(gdfRelief,basin)
        gdfsRelief.append(gdfFormated)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return    
    gdfMostColumns = max(gdfsRelief, key=lambda df: len(df.columns))
    gdfFinal = gpd.pd.concat(gdfsRelief, ignore_index=False, axis=0, sort=False)
    gdfFinal = gdfFinal.reindex(columns=gdfMostColumns.columns)
    gdfFinal.to_csv(path, index=True, header=True, float_format='%.' + str(decimalPlaces)+ 'f')

    return

def calculateTectonicParameters(drainageBasinLayer,streamLayer,demLayer,path,feedback,decimalPlaces,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nPointsMidline,nSectionsSL,mountainFronts,nPointsValley,limitDescendValley,nPointsBs):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfConcatenateds = []
    
    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    mountainFrontsInsideLayer = selectFrontsInsideLayer(mountainFronts, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    gdfFronts = createGdfFront(mountainFrontsInsideLayer)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside)
        gdfLinear = createGdfLinear(gdfStreamsInside)
        calculateStreamNumber(gdfStreamsInside,gdfLinear)
        calculateTotalStreamLength(gdfStreamsInside,gdfLinear)
        if feedback.isCanceled():
            return

        gdfTectonic = createGdfTectonic()
        calculateBasinLength(gdfStreamsInside,gdfShape,basin,feedback,useLongestRiver,gdfTectonic,tectonic=True,nPoints=nPointsBs)
        skelet = calculateVoronoiSkeleton(gdfShape, nPointsMidline, min_length=0.0)
        midline = longestPath(skelet)
        TransverseTopographicSymmetryFactor(midline, gdfStreamsInside, gdfShape, gdfTectonic, nPoints, basin, feedback, useLongestRiver)
        assimetryIndex(gdfShape, gdfStreamsInside, gdfTectonic, useLongestRiver)
        calculateSLindexMainChannel(gdfStreamsInside,demLayer,gdfTectonic,useLongestRiver, nSectionsSL)
        if feedback.isCanceled():
            return
        valleyFloorWidthHeight(gdfStreamsInside, gdfShape, nPointsValley, demLayer, gdfTectonic, limitForValleyFloor, minForValleyHeight, feedback, useLongestRiver,limitDescendValley)
        mountainFrontsInsidebasin = selectStreamsInsideBasin(gdfFronts, gdfShape, basin, feedback, streams=False)
        mountainFrontSinuosity(mountainFrontsInsidebasin, gdfTectonic)
        gdfConcatenated = formatGdfTectonic(gdfTectonic, basin)
        gdfConcatenateds.append(gdfConcatenated)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return

    gdfMostColumns = max(gdfConcatenateds, key=lambda df: len(df.columns))
    gdfFinal = gpd.pd.concat(gdfConcatenateds, ignore_index=False, axis=0, sort=False)
    gdfFinal = gdfFinal.reindex(columns=gdfMostColumns.columns)
    gdfFinal.to_csv(path, index=True, header=True, float_format='%.' + str(decimalPlaces)+ 'f')

    return

def runAllMorphometricParameters(drainageBasinLayer,streamLayer,demLayer,path,feedback,decimalPlaces,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nPointsMidline,nSectionsSL,mountainFrontLayer,nPointsValley,limitDescendValley,nPointsBs):
    demArray,noData,gt,proj,rows,cols = loadDEM(demLayer)

    calculateMorphometrics(demArray,noData,gt,proj,rows,cols,drainageBasinLayer,streamLayer,demLayer,path,feedback,decimalPlaces,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nPointsMidline,nSectionsSL,mountainFrontLayer,nPointsValley,limitDescendValley,nPointsBs)

def runReliefParameters(drainageBasinLayer,streamLayer,demLayer,path,feedback,decimalPlaces,useLongestRiver):
    demArray,noData,gt,proj,rows,cols = loadDEM(demLayer)

    calculateReliefParameters(demArray,noData,gt,proj,rows,cols,drainageBasinLayer,streamLayer,demLayer,path, feedback,decimalPlaces,useLongestRiver)

def createGdfParameters(demArray,noData,gt,proj,rows,cols,drainageBasinLayer,streamLayer,demLayer,feedback,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nPointsMidline,nSectionsSL,mountainFronts,nPointsValley,limitDescendValley,nPointsBs):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfConcatenateds = []
    
    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback)
    mountainFrontsInsideLayer = selectFrontsInsideLayer(mountainFronts, drainageBasinLayer, feedback)
    gdfStream = createGdfStream(streamsInside)
    gdfFronts = createGdfFront(mountainFrontsInsideLayer)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape, basin, feedback, streams=True)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside)
        gdfLinear = createGdfLinear(gdfStreamsInside)
        calculateStreamNumber(gdfStreamsInside,gdfLinear)
        calculateTotalStreamLength(gdfStreamsInside,gdfLinear)
        calculateMeanStreamLength(gdfStreamsInside,gdfLinear)
        calculateStreamLengthRatio(gdfLinear)
        calculateStreamLengthRatioMean(gdfLinear)
        calculateBifurcationRatio(gdfLinear)
        calculateBifurcationRatioMean(gdfLinear)
        calculateRhoCoefficient(gdfLinear)
        calculateSinuosityIndex(gdfStreamsInside,gdfLinear,useLongestRiver)
        if feedback.isCanceled():
            return
        calculateAreaPerimeter(gdfShape)
        calculateFitnessRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver)
        gdfTectonic = createGdfTectonic()
        calculateBasinLength(gdfStreamsInside,gdfShape,basin,feedback,useLongestRiver,gdfTectonic,tectonic=True,nPoints=nPointsBs)
        calculateWanderingRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver)
        calculateDrainageDensity(gdfShape,gdfLinear)
        calculateStreamFrequency(gdfShape,gdfLinear)
        calculateDrainageTexture(gdfShape,gdfLinear)
        calculateLengthOverlandFlow(gdfLinear)
        calculateConstantChannel(gdfLinear)
        calculateDrainageIntensity(gdfLinear)
        calculateInfiltrationNumber(gdfLinear)
        calculateCirculatoryRatio(gdfShape)
        calculateElongationRatio(gdfShape)
        calculateFormFactor(gdfShape)
        calculateLemniscateRatio(gdfShape)
        calculateShapeIndex(gdfShape)
        calculateCompactnessCoefficient(gdfShape)
        if feedback.isCanceled():
            return
        gdfRelief = createGdfRelief()
        calculateMinMaxMeanElevation(demArray,noData,gt,proj,rows,cols,basin,gdfRelief,feedback)
        calculateRelief(gdfRelief)
        calculateReliefRatio(gdfRelief,gdfShape)
        calculateRelativeRelief(gdfRelief,gdfShape)
        calculateRuggednessNumber(gdfRelief,gdfLinear)
        calculateDissectionIndex(gdfRelief)
        calculateGradientRatio(gdfStreamsInside,gdfLinear,demLayer,gdfRelief,useLongestRiver)
        if feedback.isCanceled():
            return
        skelet = calculateVoronoiSkeleton(gdfShape, nPointsMidline, min_length=0.0)
        midline = longestPath(skelet)
        TransverseTopographicSymmetryFactor(midline, gdfStreamsInside, gdfShape, gdfTectonic, nPoints, basin, feedback, useLongestRiver)
        assimetryIndex(gdfShape, gdfStreamsInside, gdfTectonic, useLongestRiver)
        calculateSLindexMainChannel(gdfStreamsInside,demLayer,gdfTectonic,useLongestRiver, nSectionsSL)
        if feedback.isCanceled():
            return
        valleyFloorWidthHeight(gdfStreamsInside, gdfShape, nPointsValley, demLayer, gdfTectonic, limitForValleyFloor, minForValleyHeight, feedback, useLongestRiver, limitDescendValley)
        mountainFrontsInsidebasin = selectStreamsInsideBasin(gdfFronts, gdfShape, basin, feedback, streams=False)
        mountainFrontSinuosity(mountainFrontsInsidebasin, gdfTectonic)
        gdfConcatenated = createGdfConcatenated(gdfLinear,gdfShape,gdfRelief,basin,gdfTectonic)
        gdfConcatenateds.append(gdfConcatenated)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return

    gdfMostColumns = max(gdfConcatenateds, key=lambda df: len(df.columns))
    gdfFinal = gpd.pd.concat(gdfConcatenateds, ignore_index=False, axis=0, sort=False)
    gdfFinal = gdfFinal.reindex(columns=gdfMostColumns.columns)
    return gdfFinal