# -*- coding: utf-8 -*-

'''
/***************************************************************************
 DrainageBasinGeomorphology
                                 A QGIS plugin
 This plugin provides tools for geomorphological analysis in drainage basins.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-22
        copyright            : (C) 2025 by João Vitor Pimenta
        email                : jvpjoaopimenta@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
'''

__author__ = 'João Vitor Pimenta'
__date__ = '2025-03-22'
__copyright__ = '(C) 2025 by João Vitor Pimenta'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessingException, QgsFeature
import geopandas as gpd
import numpy as np
from .parametersProcessing import (
    getStreamsInsideLayer,
    createGdfStream,
    obtainFirstAndLastPoint,
    createOrderColumn,
    fillOrder,
    mergeStreams,
    createGdfShape,
    selectStreamsInsideBasin,
    calculateStreamLength,
    createGdfLinear,
    calculateStreamNumber,
    calculateTotalStreamLength,
    calculateMeanStreamLength,
    calculateStreamLengthRatio,
    calculateStreamLengthRatioMean,
    calculateBifurcationRatio,
    calculateBifurcationRatioMean,
    calculateRhoCoefficient,
    calculateSinuosityIndex,
    calculateAreaPerimeter,
    calculateFitnessRatio,
    calculateBasinLength,
    calculateWanderingRatio,
    calculateDrainageDensity,
    calculateStreamFrequency,
    calculateDrainageTexture,
    calculateLengthOverlandFlow,
    calculateConstantChannel,
    calculateDrainageIntensity,
    calculateInfiltrationNumber,
    calculateCirculatoryRatio,
    calculateElongationRatio,
    calculateFormFactor,
    calculateLemniscateRatio,
    calculateShapeIndex,
    calculateCompactnessCoefficient,
    createGdfRelief,
    calculateMinMaxMeanElevation,
    calculateRelief,
    calculateReliefRatio,
    calculateRelativeRelief,
    calculateRuggednessNumber,
    calculateDissectionIndex,
    calculateGradientRatio,
    createGdfTectonic,
    calculateVoronoiSkeleton,
    longestPath,
    TransverseTopographicSymmetryFactor,
    assimetryIndex,
    calculateSLindexMainChannel,
    valleyFloorWidthHeight,
    createGdfConcatenated,
    loadDEM
)

def verifyLibs():
    try:
        import geopandas
    except ImportError:
        raise QgsProcessingException('Geopandas library not found, please install it and try again.')
    try:
        import numpy
    except ImportError:
        raise QgsProcessingException('Numpy library not found, please install it and try again.')
def calculateMorphometrics(demArray,noData,gt,proj,rows,cols,drainageBasinLayer,streamLayer,demLayer,feedback,precisionSnapCoordinates,minimumChannelLength,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nSectionsSL):
    feedback.setProgress(0)
    total = drainageBasinLayer.featureCount()
    step = 100.0 / total if total else 0

    gdfConcatenateds = []
    
    streamsInside = getStreamsInsideLayer(streamLayer, drainageBasinLayer, feedback, precisionSnapCoordinates)
    gdfStream = createGdfStream(streamsInside)
    obtainFirstAndLastPoint(gdfStream)
    createOrderColumn(gdfStream)
    fillOrder(gdfStream)
    mergeStreams(gdfStream)

    for idx, basin in enumerate(drainageBasinLayer.getFeatures()):
        feedback.setProgressText('Basin id '+str(basin.id())+' processing starting...')
        gdfShape = createGdfShape(basin)
        gdfStreamsInside = selectStreamsInsideBasin(gdfStream, gdfShape)
        if feedback.isCanceled():
            return
        calculateStreamLength(gdfStreamsInside,minimumChannelLength)
        gdfLinear = createGdfLinear(gdfStreamsInside)
        calculateStreamNumber(gdfStreamsInside,gdfLinear)
        calculateTotalStreamLength(gdfStreamsInside,gdfLinear)
        calculateMeanStreamLength(gdfStreamsInside,gdfLinear)
        calculateStreamLengthRatio(gdfLinear)
        calculateStreamLengthRatioMean(gdfLinear)
        calculateBifurcationRatio(gdfLinear)
        calculateBifurcationRatioMean(gdfLinear)
        calculateRhoCoefficient(gdfLinear)
        calculateSinuosityIndex(gdfStreamsInside,gdfLinear,useLongestRiver,precisionSnapCoordinates)
        if feedback.isCanceled():
            return
        calculateAreaPerimeter(gdfShape)
        calculateFitnessRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver,precisionSnapCoordinates)
        calculateBasinLength(gdfStreamsInside,gdfShape,basin,feedback,useLongestRiver,precisionSnapCoordinates)
        calculateWanderingRatio(gdfShape,gdfLinear,gdfStreamsInside,useLongestRiver,precisionSnapCoordinates)
        calculateDrainageDensity(gdfShape,gdfLinear)
        calculateStreamFrequency(gdfShape,gdfLinear)
        calculateDrainageTexture(gdfShape,gdfLinear)
        calculateLengthOverlandFlow(gdfLinear)
        calculateConstantChannel(gdfLinear)
        calculateDrainageIntensity(gdfLinear)
        calculateInfiltrationNumber(gdfLinear)
        calculateCirculatoryRatio(gdfShape)
        calculateElongationRatio(gdfShape)
        calculateFormFactor(gdfShape)
        calculateLemniscateRatio(gdfShape)
        calculateShapeIndex(gdfShape)
        calculateCompactnessCoefficient(gdfShape)
        if feedback.isCanceled():
            return
        gdfRelief = createGdfRelief()
        calculateMinMaxMeanElevation(demArray,noData,gt,proj,rows,cols,basin,gdfRelief,feedback)
        calculateRelief(gdfRelief)
        calculateReliefRatio(gdfRelief,gdfShape)
        calculateRelativeRelief(gdfRelief,gdfShape)
        calculateRuggednessNumber(gdfRelief,gdfLinear)
        calculateDissectionIndex(gdfRelief)
        calculateGradientRatio(gdfStreamsInside,gdfLinear,demLayer,gdfRelief,useLongestRiver,precisionSnapCoordinates)
        if feedback.isCanceled():
            return
        gdfTectonic = createGdfTectonic()
        skelet = calculateVoronoiSkeleton(gdfShape, n_points=50, min_length=0.0)
        midline = longestPath(skelet)
        TransverseTopographicSymmetryFactor(midline, gdfStreamsInside, gdfShape, gdfTectonic, nPoints, basin, feedback, useLongestRiver,precisionSnapCoordinates)
        assimetryIndex(gdfShape, gdfStreamsInside, gdfTectonic, useLongestRiver,precisionSnapCoordinates)
        calculateSLindexMainChannel(gdfStreamsInside,demLayer,gdfTectonic,useLongestRiver, precisionSnapCoordinates, nSectionsSL)
        valleyFloorWidthHeight(gdfStreamsInside, gdfShape, nPoints, demLayer, gdfTectonic, limitForValleyFloor, minForValleyHeight, feedback, useLongestRiver,precisionSnapCoordinates)
        gdfConcatenated = createGdfConcatenated(gdfLinear,gdfShape,gdfRelief,basin,gdfTectonic)
        gdfConcatenateds.append(gdfConcatenated)

        barProgress = int((idx + 1) * step)
        feedback.setProgress(barProgress)
        feedback.setProgressText('Basin id '+str(basin.id())+' processing completed')

    if feedback.isCanceled():
        return

    gdfMostColumns = max(gdfConcatenateds, key=lambda df: len(df.columns))
    gdfFinal = gpd.pd.concat(gdfConcatenateds, ignore_index=False, axis=0, sort=False)
    gdfFinal = gdfFinal.reindex(columns=gdfMostColumns.columns)

    return gdfFinal

def jenksBreaks(data, n_classes):
    data = np.sort(np.asarray(data, dtype=float))
    n = len(data)
    if n < n_classes:
        raise QgsProcessingException('Insufficient data for Fisher-Jenks classification without any class colapse.')
    mat1 = np.full((n + 1, n_classes + 1), np.inf)
    mat2 = np.zeros((n + 1, n_classes + 1), dtype=int)
    mat1[0, :] = 0.0

    cumsum = np.zeros(n + 1)
    cumsum_sq = np.zeros(n + 1)

    for i in range(1, n + 1):
        cumsum[i] = cumsum[i - 1] + data[i - 1]
        cumsum_sq[i] = cumsum_sq[i - 1] + data[i - 1] ** 2

    for j in range(1, n_classes + 1):
        for i in range(1, n + 1):
            for m in range(j - 1, i):
                w = i - m
                s1 = cumsum[i] - cumsum[m]
                s2 = cumsum_sq[i] - cumsum_sq[m]
                variance = s2 - (s1 * s1) / w

                val = mat1[m, j - 1] + variance
                if val < mat1[i, j]:
                    mat1[i, j] = val
                    mat2[i, j] = m

    breaks = np.zeros(n_classes + 1)
    breaks[-1] = data[-1]

    idx = n
    for j in range(n_classes, 0, -1):
        idx = mat2[idx, j]
        breaks[j - 1] = data[idx - 1]
    breaks[0] = data[0]

    if len(np.unique(breaks)) != len(breaks):
        equalValues = breaks[np.where(np.diff(breaks) == 0)[0][0]]
        data = data[data != equalValues]
        newBreaks = jenksBreaks(data, n_classes)
        breaks[0] = float('-inf')
        breaks[-1] = float('inf')
        return newBreaks

    breaks[0] = float('-inf')
    breaks[-1] = float('inf')
    return breaks

def calcWMCIFS(drainageBasinLayer,streamLayer,demLayer,feedback,precisionSnapCoordinates,decimalPlaces,selectedParametersDirectly,selectedParametersInversely,pathCorrMatrix,pathRankCp,basinsRanked,pathParameters,minimumChannelLength,pathParametersStandardized,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nSectionsSL):

    demArray, noData, gt, proj, rows, cols = loadDEM(demLayer)

    if selectedParametersDirectly and selectedParametersInversely is None:
        raise QgsProcessingException('No parameters were selected.')
    
    equals = set(selectedParametersDirectly) & set(selectedParametersInversely)

    if equals:
        nameEquals = ", ".join(map(str, equals))
        raise QgsProcessingException(
            'The same parameter cannot be selected for both the directly proportional and inversely proportional parameter lists, the following parameters were selected in both lists: ' + str(nameEquals)
        )

    allSelectedParameters = selectedParametersDirectly + selectedParametersInversely
    if 'None' in allSelectedParameters:
        allSelectedParameters.remove('None')

    gdfMorpParam = calculateMorphometrics(demArray,noData,gt,proj,rows,cols,drainageBasinLayer,streamLayer,demLayer,feedback,precisionSnapCoordinates,minimumChannelLength,nPoints,limitForValleyFloor,minForValleyHeight,useLongestRiver,nSectionsSL)
    gdfMorpParam = gdfMorpParam[allSelectedParameters]
    gdfMorpParam.to_csv(pathParameters, index=True, header=True, float_format='%.' + str(decimalPlaces)+ 'f')

    for col in allSelectedParameters:
        basinsWithNan = gdfMorpParam[gdfMorpParam[col].isna()].index.tolist()
        
        for basin in basinsWithNan:
            feedback.pushWarning(str(basin) + ' does not have the morphometric parameter ' + str(col) + ' so the parameter will be ignored in the analysis.')


    gdfWithSelectedParametersStandard = gdfMorpParam.loc[:, allSelectedParameters].dropna(axis=1)
    selectedParametersDirectly = [col for col in selectedParametersDirectly if col in gdfWithSelectedParametersStandard.columns]
    selectedParametersInversely = [col for col in selectedParametersInversely if col in gdfWithSelectedParametersStandard.columns]

    for col in selectedParametersDirectly:
        vmin = gdfWithSelectedParametersStandard[col].min()
        vmax = gdfWithSelectedParametersStandard[col].max()

        if vmax != vmin:
            gdfWithSelectedParametersStandard[col] = (gdfWithSelectedParametersStandard[col] - vmin) / (vmax - vmin)
        else:
            feedback.pushWarning('The parameter ' + str(col) + ' variation is 0, making standardization impossible.')

    for col in selectedParametersInversely:
        vmin = gdfWithSelectedParametersStandard[col].min()
        vmax = gdfWithSelectedParametersStandard[col].max()

        if vmax != vmin:
            gdfWithSelectedParametersStandard[col] = 1 - (gdfWithSelectedParametersStandard[col] - vmin) / (vmax - vmin)
        else:
            feedback.pushWarning('The parameter ' + str(col) + ' variation is 0, making standardization impossible.')

    gdfWithSelectedParametersStandard.to_csv(pathParametersStandardized, index=True, header=True, float_format='%.' + str(decimalPlaces)+ 'f')
    columns = gdfWithSelectedParametersStandard.columns

    gdfWithSelectedParametersStandard = gpd.pd.DataFrame(gdfWithSelectedParametersStandard, columns=columns)

    X = gdfWithSelectedParametersStandard.values

    covMatrix = np.corrcoef(X, rowvar=False)
    paramNames = columns

    dfCorr = gpd.pd.DataFrame(covMatrix, columns=paramNames, index=paramNames)

    colSums = dfCorr.sum(axis=0)
    totalSum = dfCorr.values.sum()

    weights = colSums / totalSum

    wmciDirect = gdfWithSelectedParametersStandard.loc[:, selectedParametersDirectly]
    wmciInverse = gdfWithSelectedParametersStandard.loc[:, selectedParametersInversely]

    rankingPerParam = gpd.pd.concat([wmciDirect, wmciInverse], axis=1)

    weightedRanking = rankingPerParam * weights
    vulnerabilityIndex = weightedRanking.sum(axis=1)

    ranking = vulnerabilityIndex.rank(method='min', ascending=False)

    nClasses = 5

    breaks = jenksBreaks(vulnerabilityIndex, nClasses)

    priorityJenks = np.digitize(vulnerabilityIndex.values, breaks[1:-1], right=True) +1

    priorityLabels = {
        1: "Very low",
        2: "Low",
        3: "Medium",
        4: "High",
        5: "Very high"
    }

    priorityText = np.vectorize(priorityLabels.get)(priorityJenks)

    dfCorr.to_csv(pathCorrMatrix, index=True, float_format='%.' + str(decimalPlaces)+ 'f')

    rankingPerParam["Watershed Morphometric Composite Index (WMCI)"] = vulnerabilityIndex
    rankingPerParam["Ranking"] = ranking
    rankingPerParam["Priority"] = priorityText

    rankingPerParam = gpd.pd.concat(
        [weightedRanking, 
            rankingPerParam["Watershed Morphometric Composite Index (WMCI)"],
            rankingPerParam["Ranking"],
            rankingPerParam["Priority"]],
        axis=1
    )

    rankingPerParam.to_csv(pathRankCp, index=True, float_format='%.' + str(decimalPlaces)+ 'f')

    for i, feat in enumerate(drainageBasinLayer.getFeatures()):
        f = QgsFeature()
        f.setGeometry(feat.geometry())
        attrs = feat.attributes()
        attrs.append(float(ranking.iloc[i]))
        attrs.append(str(priorityText[i]))
        f.setAttributes(attrs)

        basinsRanked.addFeature(f)